reposense/RepoSense

docs/developer_guide.md
To get the ball rolling -> borrowed most of it from addressbook 😛
=> DeveloperGuide: add setup instructions

README.md
=> README: embed travis status badge

src/test/java/util/TestConstants.java
Fix #73 
Test repo created at https://github.com/reposense/testrepo-Alpha
=> Move test repos inside reposense org #73

README.md, appveyor.yml
Proposed message
```
AppVeyor is a continuous integration service, similar to Travis but uses Windows virtual machines.
Also, employing a secondary service allows it to be executed in parallel with current CI service.
Let's integrate AppVeyor support in our pull request checks to prevent our application fails
on Windows machines.
```
=> Setup AppVeyor CI

docs/UserGuide.md
@eugenepeh the user guide is ready to be merged. are these the changes you are looking for?
=> Frontend: update the user guide

src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/authorship.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json, src/main/java/reposense/report/ReportGenerator.java, src/test/java/reposense/parser/RepoConfigurationTest.java
```
RepoSense/testrepo-Delta has been updated with the author
aliases for each author for testing if author aliases will be
added correctly from the _reposense/config.json config file.
Let's update the data for unit and functional test to consider those
aliases as well.
```
=> Update data for testrepo-Delta

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_authorship.js
=> De emphasize untouched code

frontend/src/index.jade, frontend/src/static/css/style.scss
fixes #270, fixes #184 
```
The tabs bar seems to serve no purpose.
Let's remove it since its not needed.
```
=>  Dashboard: remove unused icon in the code view #270 

frontend/src/index.jade, frontend/src/static/css/style.scss
part of #259 
```
New users are confused as to how to view the code from an author.
Let's add a tooltip to the ramp chart title so that new users can
intuitively know how to view code.
```
=>  Dashboard: add an indicator to code view

frontend/src/index.jade, frontend/src/static/css/style.scss
fixes #258 
```
Layout not very optimized, settings looks messy and takes up a lot of
space.
Let's reduce the font size for the values to make the settings look
neater.
```
=> Dashboard: optimize settings bar to fit various screen sizes #258

README.md
=> List RepoSense team in the README.md #293

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_authorship.js
Fixes #369 
```
Code panel shows only contribution lines per file.
Let's display total contribution of author in code panel to make this
information more clearly visible for users.
```
=> Show total contribution in code panel #369

docs/UserGuide.md
Fixes #297 
```
Our UserGuide does not have a FAQ section.
Let's add a FAQ section in our UserGuide to address common questions
and issues, allowing users troubleshoot them themselves.
```
=> User Guide: add FAQ section to address common problems #297

frontend/src/index.jade
=> add link for commit view

.eslintrc.json
=> Add rule to ESLint

.eslintrc.json, frontend/src/static/js/main.js
=> Add indent rule to ESLint

.eslintrc.json, frontend/src/static/js/api.js
=> ESLint: enforce indentation for ArrayExpression

frontend/src/summary_charts.pug, package.json
Quick follow up to https://github.com/reposense/RepoSense/pull/1179#issuecomment-635830606
```
Add summary_charts to puglint file list
```
=> Add summary_charts to puglint file list

docs/dg/settingUp.md, docs/dg/workflow.md
Updated to reflect changes over at se-edu/guides side.
```
DG: Fix incorrect tutorial links
```
=> DG: Fix incorrect tutorial links

docs/_markbind/navigation/ugSiteNav.md
The diff is self-explanatory.
```
UG: Fix siteNav swapped links
```
=> UG: Fix siteNav swapped links

frontend/cypress/.eslintrc.json, frontend/cypress/tests/chartView/chartView_errorSummary_messageBox.js, frontend/cypress/tests/codeView/codeView.js, frontend/cypress/tests/codeView/codeView_load_benchmark.js, frontend/package.json
Closes #1564 
```
For the frontend, the current "lint" script does not pick up files
under the "cypress" folder.
This should be fixed so that any programmatic and stylistic errors in
these files can be detected and corrected.
Let's add the files under the "cypress" folder to the lint script
and fix violations of the existing code.
```
=> [#1564] Lint script: add files under cypress folder

README.md
```
Update README.md status badges
Some of the status badges on the README.md file are outdated
and/or are no longer working.
Let's update the README.md file with the new status badges and
remove the outdated ones.
```
=> README.md: update status badges

.github/workflows/integration.yml
```
The node-version semantic used for cypress does not match those in other
jobs.
Let's change the node-version semantic for cypress.
```
=> GitHub Actions: Change node version semantic for Cypress

frontend/src/app.vue, frontend/src/store/store.js, frontend/src/utils/api.js, frontend/src/views/v-authorship.vue, frontend/src/views/v-summary.vue
Fixes #1784
```
The frontend loading screen was unable to unload, causing
Cypress CI tests to fail. This is likely due to the browser lazy
rendering the loading screen which caused it to not react
properly.
I am unsure why this issue surfaced recently, however it is likely
due to a breaking change in some dependency. It might also
be caused by a recent chrome update.
Lets fix the issue by forcing the browser to rerender when the
loading screen needs to appear.
```
To prevent breaking dependency changes, suggest committing `package-lock.json` .
=> Fix frontend loading screen

.github/workflows/delete-deploy.yml, .github/workflows/gh-pages.yml, .github/workflows/integration.yml, .github/workflows/pending.yml, .github/workflows/stale.yml, .github/workflows/surge.yml
```
Many actions that we use have been updated. Most of the updates are
related to the underlying actions upgrading from Node 12 to 16.
Let's use the updated versions in our workflows.
```
Although the updated actions use Node 16 in their underlying implementation, it does not appear to affect CI even though we are using Node 14.
The `distribution` used here is `zulu` since that is the [originally supported distribution in `v1`](https://github.com/actions/setup-java#v2-vs-v1). On another note, legacy Java syntax such as `1.8` was also dropped in `v2`.
=> GitHub Actions: update deps to latest versions

docs/about.md
```
The CDTL link in about.md is different from the actual one in use. In
addition, the GitHub link for one contributor appears to have changed.
The link with the original name no longer works.
Let's update the links.
```
~~I wish to have #1776 merged before this so that this PR can pass CI.~~
Taking back the above since this is a pure documentation change.
=> Docs: fix broken links in about.md

frontend/.eslintrc.json, frontend/src/utils/api.js, frontend/src/views/v-zoom.vue
```
There is a mismatch between the JavaScript line length limit allowed
in .eslintrc.json and the hard limit in the coding standard.
Let's change the allowed limit in .eslintrc.json and update the files
that fail the check upon this change.
```
Reference: https://se-education.org/guides/conventions/javascript.html
=> Frontend: change JavaScript line length limit for ESLint

.github/workflows/integration.yml
Fixes #1764 
```
The Install packages step looks for a non-existent package.json file.
The Set up Cypress step is basically a repeat of installCypress within
build.gradle, which runs before frontendTest task.
Let's remove both steps from Cypress CI.
```
=> [#1764] Actions: refactor Cypress CI build step

frontend/src/views/v-authorship.vue
Fixes #1772 
```
The total character limit in report code view (100K) is too low. As a 
result, files are collapsed unnecessarily.
Let's raise the total character limit as a temporary fix until lazy 
loading removes the need for a total character limit.
```
=> [#1772] Increase total character threshold in code view

docs/_markbind/layouts/dg-sitenav.md, docs/dg/cli.md, docs/ug/cli.md
Part of #1645
```
Previously, new CLI syntax for testing is added under UG. However, the 
behavior is only meant for developers and not users.
Let's create a new CLI syntax page in DG and shift the information.
```
Quick fix for [this issue](https://github.com/reposense/RepoSense/pull/1816#issuecomment-1207425770).
=> [#1645] Docs: move test-related flags from UG to DG

src/systemtest/java/reposense/LocalRepoSystemTest.java, src/test/java/reposense/util/InputBuilder.java
Fixes #1818 
```
Currently, all test cases within LocalRepoSystemTest uses
String.format().
Let's change the CLI input of test cases within LocalRepoSystemTest to
use the InputBuilder class.
```
=> [#1818] Add input builder to LocalRepoSystemTest

frontend/cypress/package-lock.json, frontend/cypress/tests/codeView/codeView_filterGlob.js
Fixes #1833 
```
There is currently no testing done for the new front-end change 
in filter glob related functionalities.
This may result in regression bugs in the future.
Let's add tests for these new frontend changes made for the filter glob functionalities
to ensure this feature works as expected and facilitate future testing.
```
=> [#1833] Add frontend tests for filter glob

frontend/src/app.vue, frontend/src/components/c-ramp.vue, frontend/src/components/c-segment.vue, frontend/src/components/c-summary-charts.vue, frontend/src/utils/api.js, frontend/src/utils/repo-sorter.js, frontend/src/utils/safari_date.js, frontend/src/views/c-authorship.vue, frontend/src/views/c-summary.vue
Fixes #1073
```
There are several .vue files that use string concatenation instead.
This is rather messy for lines with a lot of variables concatenated
together. Opting for string interpolation improves code readability.
Let's use ES6's way of string interpolation for such files.
```
=> [#1073] Use ES6+ way for string interpolation

frontend/src/views/c-authorship.vue
Fixes #1843 
```
The labels on top of the files in `c-authorship.vue` display the LoC of
all the files that the author has written to. This is not the intended
action.
Let us update the logic for this calculation to ensure that the labels
correctly display the LoC.
```
=> [#1843] Fix authorship label LoC

frontend/cypress/tests/chartView/chartView_zoomFeature.cy.js
Fixes #2045 
```
Currently, Cypress zoom feature tests are failing due to a recent change
in behavior caused by a bug fix. With the tests failing, we are unable
to detect any future regressions.
Let's update the Cypress tests to test for the new intended behavior.
```
* Original point (200, 20) has been replaced by (185, 20), as it seems that the choice of (200, 20) leads to potentially non-deterministic behavior, i.e. Cypress test fails sometimes, but not others.
* Choice of (180, 20) is a boundary point, making it sensitive to small regressions, while being seemingly deterministic.
=> [#2045] Fix cypress zoom feature test

frontend/public/title.md
Fixes #2204
```
Remove Unexpected Title
Adding a title.md to the public folder has caused the title feature to
become opt-out instead of opt-in. This is not the intended way for the
title feature to be used.
Let's remove the title.md file.
```
=> [#2204] Remove Unexpected Title

docs/_markbind/variables.json, docs/_markbind/variables.md, docs/dg/architecture.md, docs/dg/report.md, docs/dg/settingUp.md, docs/index.md, docs/ug/cli.md, docs/ug/configFiles.md, docs/ug/customizingReports.md, docs/ug/faq.md, docs/ug/generatingReports.md, docs/ug/usingAuthorTags.md, docs/ug/usingReports.md
Reopening PR #2218 without merge commits.
=> Fix some minor cosmetic issues in docs

.github/workflows/integration.yml
Fixes #2231
```
Given that the macos-11 GitHub Runner has been decommissioned, let's
move to migrate to macos-12 and macos-13 GitHub Runners to fix the
issue of failing CI.
```
N/A
=> [#2231] CI failing for macos-11 JDK 11

docs/dg/workflow.md, src/main/java/reposense/authorship/FileInfoAnalyzer.java
Fixes #1981
```
The link under 'Workflow' section of DG only links to frontend and
backend issues.
Let's link them to all types of first timer issues so that new 
contributors do not miss out on some other types of issues, such as 
DevOps.
```
Before:
After:
=> [#1981] Change link to link to all first timer issues

docs/ug/runSh.md
Related to #2208 and addresses comments by @damithc in reposense/publish-RepoSense#12
```
Update User Guide to describe --latest tag in publish-RepoSense
```
=> Update User Guide to describe --latest tag in publish-RepoSense

.github/workflows/integration.yml
Part of #2252 
```
Add ubuntu-24.04 to CI runners
This PR updates the CI configuration to include Ubuntu 24.04 as one 
of the runners. This ensures that our code is tested on the latest
Ubuntu version, providing better compatibility and early detection
of potential issues.
```
N/A
=> [#2252] Add ubuntu-24.04 to CI runners

.github/workflows/integration.yml
Fixes #2277 
```
Update environment setting-up method
The current cypress frontend test fails during CI run at the state of
setting up environment
Let's modify actions for setting-up state and update the apt package
before installing relevant packages
```
=> [#2277] Fix cypress setting up error

build.gradle
Fixes #1952
```
Add description to Gradle tasks for better readability
```
=> [#1952] Add description to Gradle tasks

renovate.json
Fixes #2333
```
Add Renovate to automate package upgrades
Let's add Renovate to further automate our dependency update process.
```
=> [#2333] Add Renovate

.github/workflows/integration.yml
Fixes #2465
```
The image runner of windows 2019 is
deprecated.
Let's remove the outdated version
of runner image and and the new
windows 2025 runner image.
```
=> [#2465] Update windows runner image version
