build.gradle, docs/Build.md, docs/user_guide.md
Gradle build compiles our source files and libraries used in the program into separate jar files, and delivers the entire package as a zip file.
It is rather inconvenient as user would have to extract from the zip file to use it and also have more unnecessary files to deal with. Additionally, if we package only our own class files into the JAR file, it will not work properly unless the user has all the other JAR files (i.e. third party libraries) our classes depend on.
Let's replace the gradle build with shadowJar plugin to package all dependencies into a single JAR file which enhance usability and portability.
=> Gradle: replace build with shadowJar plugin

.travis.yml, build.gradle, docs/developer_guide.md, docs/user_guide.md, gradle/wrapper/gradle-wrapper.properties
Fix #81. Seems easier than I thought... have nothing else to fix other than url 🤣 
Proposed message:
```
Gradle does not recognise Java 9 version.
This is likely due to gradle version being out-dated for too long.
Let's update gradle to latest version so that it is compatible with the newer version of Java.
```
Onhold till #68 is merged so that I can update the docs too.
=> Gradle: upgrade to version 4.7

build.gradle
The jar file built by gradle shadowjar plugin throws a could not find or load main class error.
This is due to the recent renaming of packages in the project and the mainClassName in gradle wasn't updated correspondingly.
Let's apply this fix in the build.gradle.
=> Fix main class could not be found

src/main/java/reposense/analyzer/ContentAnalyzer.java, src/main/java/reposense/analyzer/RepoAnalyzer.java, src/main/java/reposense/dataobject/RepoInfo.java, src/main/java/reposense/report/RepoInfoFileGenerator.java
Part of #69 
Proposed message:
```
Separate the association between Commits and Authorship analysis is
necessary for us to match the proposed architecture in #69. 
Let's start by removing FileInfo from RepoInfo model.
```
=> Remove RepoInfo's dependency on FileInfo #69

template/index.html, template/repo_report/index.html, template/static/scripts/utils.js
proposed message
```
We wanna generate the report for each repo iteratively to improve
performance.
Assume files converted into JSON formatted, rather than the initial JS
script which loads all the information into a pre-defined variable
name.
Assume folders reorganized to support the multiple reports format. This
potentially frees up the reporting capabilities of reposense, making it
possible for other developers to extend upon the generated results.
Template is updated to display the separated results through the means
of artifically merging them through dummy files like `summary.js` and
`report.js`.
Let's work on the template, it is temporary and work will commence on a 
seperated single file template to load the reports.
```
=> updated template to fake merge separated reports

template/index.html, template/static/scripts/summaryVueMethods.js, template/static/scripts/utils.js
template: add padding to front of ramp slices. also make slices fill …
```
Ever since the splitting of the results, repositories which starts from 
different dates have problem aligning themselves.
Let's pad the ramp slices array with empty results to align all the 
different repositories together.
```
=> Align ramp chart by date using padding

build.gradle, src/functional/java/reposense/Entry.java, src/test/java/reposense/util/TestUtil.java
Proposed message:
```
Unlike diff tools, Assert.assertEquals does not provide useful 
information when the content in 2 File objects are not the same. 
This makes troubleshooting difficult. As without a clear indication, 
it is hard to trace the errors.
Let's implement the functionality of printing line differences by 
adding the method TestUtil#compareFileContents. 
```
=> TestUtil: add file content comparison method

src/functional/java/reposense/Entry.java, src/main/java/reposense/analyzer/FileAnalyzer.java, src/main/java/reposense/analyzer/FileInfoGenerator.java, src/main/java/reposense/frontend/CliArguments.java, src/main/java/reposense/frontend/RepoSense.java, src/main/java/reposense/git/GitCloner.java, src/main/java/reposense/report/RepoInfoFileGenerator.java, src/main/java/reposense/system/CommandRunner.java, src/main/java/reposense/system/CsvConfigurationBuilder.java, src/main/java/reposense/util/FileUtil.java, src/test/java/reposense/analyzer/FileAnalyzerTest.java, src/test/java/reposense/git/GitCheckerTest.java, src/test/java/reposense/system/CommandRunnerTest.java, src/test/java/reposense/template/GitTestTemplate.java, src/test/java/reposense/util/TestUtil.java
Fixes #107 
```
java.nio.file.Path is able to do everything java.io.File can and generally in a better way. 
This is supported by the document posted on the website
https://docs.oracle.com/javase/tutorial/essential/io/legacy.html.
Let's move towards to using Path as a replacement to File whenever we can for better
exception handling and OS invariant coding.
```
=> Shift from File to Path class #107

docs/user_guide.md, src/functional/java/reposense/Entry.java, src/functional/resources/expected/CS2103AUG2017-W09-B1_main/commits.json, src/functional/resources/expected/CS2103AUG2017-W09-B2_main/commits.json, src/functional/resources/expected/summary.json, src/main/java/reposense/system/CommandRunner.java, src/main/java/reposense/util/Constants.java
```
Several date time inconsistency exists in the project.
1. Instead of designated constants, raw values are being used in month
field of Calender setter.
2. Time zone and hours were not specified in the git log command
execution.
This leads to disagreeing outputs when running the program at
different timing or on different machine.
Let's fix the date time inconsistency by
1. using the designated constants,
2. and fixed formatted values.
```
=> Fix datetime inconsistency

docs/developer_guide.md, docs/user_guide.md, src/functional/java/reposense/Entry.java, src/main/java/reposense/git/GitBlamer.java, src/main/java/reposense/system/CommandRunner.java, src/main/java/reposense/system/StreamGobbler.java, src/main/java/reposense/util/FileUtil.java
Fixes #94.
Part of #84.
```
The analyzing of contribution for each file in the program is very slow 
due to several factors:
1. The `git blame` process produces a lot of unnecessary line information, 
causing a large amount of unnecessary time spent reading I/O. 
2. StreamGobbler uses String concatenation when reading from process InputStream,
which is polynomial in time based on the number of lines.
Let's improve performance of the program and functional test by:
1. Filter the `git blame` process output using `findstr` in Windows OS or `grep`
for other OS, thus having a smaller I/O to read.
2. Change StreamGobbler to read directly from InputStream instead of using
a BufferedReader, and use StringBuilder instead of String concatenation.
```
=> Improve performance

src/test/java/reposense/parser/ArgsParserTest.java
Proposal Message:
```
ArgsParser unit tests use ClassLoader#getResource(String) to get the path to
a resource file/directory.
According to this SO post[1], ClassLoader#getResource(String) adds an extra
leading slash before a path on Windows systems, which may cause the path
we get to be invalid, resulting in all ArgsParser's unit tests to fail.
Let's update ArgsParserTest to use File(String).toPath() to prevent
the extra leading slash in Windows system.
[1]: Leading slash before disk name in Windows:
https://stackoverflow.com/questions/15662820/getresource-puts-a-leading-before-the-disk-name-using-java-1-7-windows-7
```
=> Fix failing ArgParser unit tests on Windows systems

src/main/java/reposense/system/CustomLogFormatter.java
Fixes #139 
Proposed message:
```
Currently, the logger shows a lot of extra information in console which might 
not be useful for the user.
Let's configure the logger to only show the useful information to the user. 
```
=> Clean up the logger output #139

.travis.yml, build.gradle
Fixes #143 
```
As an Java application, RepoSense is able to execute on all OSes that
supports jar executable. It is important to ensure that our application
does not break on the supported OSes.
In addition to the linux execution environment, Travis also supports CI
on macOS. Furthermore, this multi-environment configuration allows
parallel execution according to Travis-CI documentation [1].
Let's enable a second build environment, macOS, on travis, so we can
ensure RepoSense runs correctly on all supported OSes.
[1] Testing Your Project on Multiple Operating Systems:
https://docs.travis-ci.com/user/multi-os/
```
=> Make Travis-CI test RepoSense on Mac OSX #143

README.md, docs/UserGuide.md
```
Due to renaming of developer_guide.md to DeveloperGuide.md 
and user_guide.md to UserGuide.md, the links in README.md leading
to those two documents are now broken.
Let's fix those broken links.
```
=> README.md: fix broken links

src/functional/java/reposense/Entry.java, src/main/java/reposense/RepoSense.java, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/system/CommandRunnerTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #177
```
RepoSense only tracks '.java' and '.adoc' file types for analyse.
This may not be sufficient for visualization as not many other projects that
are not mainly coded in Java or use asciidoctor for their documents.
Let's include more file types by default in the analysis.
```
=> Add more default file types to analyze #177

frontend/src/static/js/api.js, frontend/src/static/js/v_summary.js, sample.csv, template/static/js/api.js, template/static/js/v_summary.js
also fixes #186 
```
When displaying contributors with no commit history, the dashboard will
crash and stop rendering ramp charts for subsequent repositories.
This is caused by the padding of the ramp charts. The padding is added
to the ramp chart to align the charts across different users and
projects.
The amount of padding required is calculated from the `sinceDate` of
the first and last date entry of the user. This becomes problematic
when the user have no date entries at all, causing the system to run
into problem, and hence, skipping the ramp chart generation for the
particular project.
To fix this, let's alter the padding function to take into the edge
case of a empty date range, and artifically fill up the whole timeline
with generated empty dates.
```
=> Fix dashboard padding function

sample.csv, src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/util/FileUtil.java, src/test/java/reposense/util/FileUtilTest.java
Fixes #194 
```
RepoSense 1.1RC2 executed as a JAR throws an InvalidPathException when
accessing templateZip.zip.
This is because the location of the templateZip.zip cannot be located
by its path on the disk but by its relative path in the JAR file. 
So let's change the way to retrieve templateZip.zip from 
RepoSense.class.getClassLoader().getResource("templateZip.zip") to 
RepoSense.class.getResourceAsStream("/templateZip.zip").
```
=> Fix invalid path when accessing jar resources  #194

docs/UserGuide.md, src/functional/java/reposense/Entry.java, src/main/java/reposense/RepoSense.java, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/main/java/reposense/model/CliArguments.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/parser/AlphanumericArgumentType.java, src/main/java/reposense/parser/ArgsParser.java, src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/parser/ArgsParserTest.java, src/test/java/reposense/system/CommandRunnerTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #56, #177
```
File formats .java and .adoc are hardcoded in the git log command of
RepoSense.
As the file formats are not changable, this means RepoSense may only
be useful for users who work on repository that consisting mainly of
java or adoc.
Let's allow an optional file formats to be passed in as a parameter so
that user could use RepoSense on repositories with different codebases.
```
=> Add support for user-supplied file formats #56, #177

build.gradle
```
build.gradle defines the destination location whereby to
generate the jar file as '{${buildDir}/jar/'.
As single quotes are being used, the ${buildDir} is taken as
a literal String rather than as a template[1] for the build folder
location. This causes the jar file to be incorrectly generated in
the project root directory instead of the build folder.
Let's update build.gradle destination location for the jar file to
use double quotes as a templatable String instead.
[1]: SO post explaining the difference between single and double quotes in Groovy:
https://stackoverflow.com/questions/6761498/whats-the-difference-of-strings-within-single-or-double-quotes-in-groovy
```
=> build.gradle: fix output location for jar file after gradle build

frontend/src/index.jade, frontend/src/static/js/v_summary.js
fixes #197, fixes #201 
```
When the dashboard loads two projects of different date range, some of
the dashboard attributes will be messed up and this affects the
rendering of the ramp charts.
More specifically, the `sliceWidth` and `sliceCount` will be affected
by the date range and will cause the dashboard to incorrectly "thinks"
that it has more slices then it actually does, and hence causing it to
be incorrectly displayed squashed up together.
Let's remove the attributes in `v_summary` and generate the width and
position of the slices from the actual array of slices instead.
```
=> Fix ramp chart positioning #197

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_summary.js
```
After the removal of the feature to support multiple reports, the navigation
bar contains only the reposense logo.
The bar now plays only an aesthetic role and has no functional purpose, which
is a waste of vertical space.
Similarly the filters on the summary tab could be more concisely displayed to
fully ultilize vertical space.
Let's make the necessary UI changes to improve vertical space usage.
```
=> Remove navbar to optimize usage of vertical space.

src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/authorship.json, src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json, src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/authorship.json, src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Beta_master/authorship.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Beta_master/commits.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Charlie_master/commits.json, src/main/java/reposense/system/CommandRunner.java
Part of #203 
```
The git blame command in CommandRunner#blameRaw(String, String)
uses copy and move detection[1] for its line authorship analysis.
These may cause an author's commit contribution and
his line contribution count on the dashboard to be inconsistent,
as a the author may have copied or moved lines from another
author, which will cause those lines to be authored to the other
author instead.
If necessary, users may use collate if they wish to identify if
certain codes belong to them, instead of us trying
to identify the 'original' author by ourselves.
Let's remove the copy and move detection in
CommandRunner#blameRaw(String, String) git blame command.
[1]: Docs on the git blame copy and move detection:
https://git-scm.com/docs/git-blame#git-blame--Mltnumgt
=> CommandRunner#blameRaw: remove copy and move detection

src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/authorship.json, src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json, src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/authorship.json, src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json, src/main/java/reposense/authorship/FileInfoAnalyzer.java, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/authorship/model/FileInfo.java, src/main/java/reposense/authorship/model/LineInfo.java, src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/system/CommandRunnerTest.java
Fixes #203 
Depends on #212 
```
When a date range is supplied, the FileInfoAnalyzer will only
git blame on the range of commits that fall within the given
date range.
This may cause the authorship of certain lines that have not
been touched at all during the date range to be incorrectly
authored to a random author that commited in that date range.
Let's update the git blame command to run the git blame from
initial to the latest commit of that date range. In addition, let's
also update FileInfoExtractor to only track lines that were added
within the date range, and add them into the final authorship count.
```
Below was edited by @eugenepeh, for reference purpose
```diff
diff --git a/docs/UserGuide.md b/docs/UserGuide.md
index 6f0b634..a8af6df 100644
--- a/docs/UserGuide.md
+++ …
```
=> Authorship: incorrect line authorship when analyzing date range #203

frontend/src/index.jade, frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js
closes #156. after #171
proposed message
```
The dashboard's overview displays the DisplayName as specified in the CSV
config file while the side panel displays the gitHub ID instead.
This may cause confusion to users as the display name and for overview and the
side panel is different.
Let's update the side panel to show the the same display name as overview.
```
=> Dashboard: synchronize code panel display name #156

src/main/java/reposense/authorship/FileInfoExtractor.java
Fixes #215:
```
FileInfoExtractor#getFilePathFromDiffPattern(String) checks
for the group pattern '+++ b/path/to/file'
within the git diff result in order to get the file path.
However, when a new and also empty file is added in between the
commit range to analysis, the file will appear in the git diff result,
but since there are no lines to display, the above group does not
get printed, thus 
FileInfoExtractor#getFilePathFromDiffPattern(String) is unable
to match the pattern, causing the program to crash.
Let's add a check to skip these new and empty files in 
the git diff result, since an empty file has no lines to 
attribute any contribution.
```
=> Extracting info from git diff is not working as expected #215

docs/UserGuide.md, sample.csv, src/functional/resources/dateRange/expected/summary.json, src/functional/resources/noDateRange/expected/summary.json, src/functional/resources/sample.csv, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/builder/ConfigurationBuilder.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/main/java/reposense/git/GitDownloader.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/parser/InvalidLocationException.java, src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/system/CommandRunner.java, src/main/java/reposense/util/Constants.java, src/main/java/reposense/util/FileUtil.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/git/GitCheckerTest.java, src/test/java/reposense/system/CommandRunnerTest.java, src/test/java/reposense/template/GitTestTemplate.java, src/test/java/reposense/util/TestConstants.java
```
Representing a repository with organization and repository name in 
the config csv file may only satisfies basic usage.
By generalizing it to location allows cloning from disk locations or using
of more complex .git links.
i.e. https://username@github.com/organization/repository.git. 
Let's use location in the config csv file to make git clone more versatile.
```
=> Allow location to be supplied into CSV Config File

docs/UserGuide.md, sample.csv, src/functional/resources/sample.csv, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/builder/ConfigurationBuilder.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/system/CommandRunnerTest.java
#Fixes #218 
```
RepoSense only accepts an inclusive list of file formats to analyze.
However, users may wish to specifically exclude analyze of some
files or folders, such as large data files or test folders, as they may
not be meaningful to analyze.
Let's add back-end support to exclude analyzing of files of specified
glob patterns, which can be done in git log by using pathspec[1].
[1] Intro to Git's pathspec:
https://kgrz.io/git-intro-to-pathspec.html
```
=> Add support for file exclusion patterns #218

frontend/src/index.jade, frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js
fixes #214
```
As the tab content is changed, some of the data for the vue module will
be overwritten and it messes up the display of the authorship tab,
causing the case where multiple files gets jumbled up together and the
display goes wild.
To prevent that from happening, let's tag the `v_authorship` module
with a key which forces vue to re-render `v_summary` as a new instance
with a fresh set of data.
```
=> Fix code panel not showing the correct files #214

frontend/src/static/css/style.scss, frontend/src/static/js/api.js, frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js
**proposed message**
```
The dashboard as of v1.1.1 is loaded dynamically after each
`commits.json` is loaded.
If the filter date range is not defined, the range will be determined
by the first and last commits of that particular repository. This start
and end dates will then be set as the filter dates to be used for later
rendering of the other repositories.
However, this leads to a problem when the repositories are of a
different date range, if the earlier repository is loaded first, the
date range will not be able to display the ramps in the later
repository, vice versa.
To fix this issue, let's only determine the date ranges after all the
`commits.json` of the repositories is loaded. However, in doing this,
we would only be able to display the ramps after all the repositories
are …
```
=> Dashboard: determine date range only after all repo data are loaded

frontend/src/static/js/v_summary.js, sample.csv
fixes #223 
```
The current dashboard as of v1.1.1a sorts the users in the repository
by the number of contributions they have made for the project in that
time period.
This however puts an unnecessary focus on the contribution LoC which
may not be a true reflection of the users' contribution. Let's change
the default view to sort the users by their names instead.
```
=> Dashboard: default view: sort by name within repo #223

frontend/src/index.jade, frontend/src/static/js/api.js, frontend/src/static/js/main.js, frontend/src/static/js/v_summary.js
fixes #224 
```
The summary dashboard plays an important role in highlighting and filtering the
report data to provide the most relevant view for the users.
Permalinks was a feature implemented in the previous dashboard that enables the
users to quickly save the state of the dashboard to quickly return to it when
needed.
While useful, this feature was not core to the usage of the dashboard, hence
left out during the feature for feature reimplementation during the dashboard
structural changes.
Lets implement this permalink feature in the main vue module. New fields will
be emitted from their individual modules into the global  object.
The summary module will read the information from the global object then load
the filtered view accordingly.
Implementing it in the main modules also …
```
=> Dashboard: restore view state using query parameters #224

frontend/src/static/js/main.js
fixes #239 
```
Microsoft Edges does not support the full set of features available in
the ES6 specification, amongst which, includes the object spread
operator. [1]
Let's remove the usage of the object spread operator so allow the
dashboard to be run from edge browser.
[1] Discussion on Edge's support for object spread operator
https://github.com/Polymer/tools/issues/173
```
=> Dashboard does not work with microsoft edge #239

frontend/src/static/css/style.scss
fixes #209 
```In some browsers (chrome, edge), the height of the content in the
"label" tag seems to be greater than the height allocated to it by the
render engine. This results in the "scrollbar" arrows popping up to
show the users the "full content".
This can be distracting for users when they are trying to navigate the
site. Let's remove this scrollbar arrows by applying the "overflow-y:
hidden" CSS setting to the filter labels.
```
=>  Some browsers show extra element #209

frontend/src/static/js/v_authorship.js
fixes #254 
```
When trying to open up the right side tab panel to load the authorship
information, the file not found error pops up, and the panel stays
blank.
Turns out, the error was introduced when we were trying to package all
the information into a single object when passing it into the module.
To fix this, let's update the way the directory whereby the file is
being loaded.
```
=> Dashboard unable to load authorship.json file #254

frontend/src/index.jade
fixes #189 
```
Ramps representing very huge commits will be rendered as a very
humongous triangle. This display blocks up the commits in the earlier
periods, hence causing them to be unclickable.
To fix this, let's render the ramps such that the earlier ramps will
have a larger z-index value to place it on top of the more recent
ramps. This ensures that users will be able to interact with all the
ramps.
```
=>  Large ramp blocks interaction of ramps under it #189

_reposense/config.json, docs/StandaloneConfiguration.md, docs/UserGuide.md, repo-config.csv, src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/authorship.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/model/StandaloneAuthor.java, src/main/java/reposense/model/StandaloneConfig.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/parser/RepoConfigurationTest.java
Fixes #244
```
Following #218, file exclusion glob patterns can be supplied in the
csv config file.
Let's decentralized this setting to the _reposense/config.json so
repository owners can apply it to their repositories.
```
=> Add repo file exclusion patterns to standalone config #244

src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/authorship.json, src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json, src/main/java/reposense/authorship/FileInfoAnalyzer.java, src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java
Fixes #262 
```
Each author has their own ignoreGlobList, which should ignore
any of their contributions to any files within that glob list.
However, while the commits information are correctly ignored,
the authorship information is not, as some files that should be
in the glob list still appeared for the author's contribution.
This is due to AnnotatorAnalyzer not ignoring the files in the
glob list, and overriding the original git blame results.
Let's resolve this by updating AnnotatorAnalyzer to remove
author contribution if the file being analyzed is inside their
glob list.
```
=> Ignore glob list does not propagate to code view #262

frontend/src/static/js/v_summary.js
fixes #263 
```
Occasionally, clicking a ramp will show no commits found for the
specified user. This is because our git log command uses a constant
timezone (Singapore UTC+8) and this mis-align with the GitHub time
system.
Let's fix this by adding the timezone to the github redirect link as
well.
```
=>  Add timezone to ramp's github redirect link #263 

author-config.csv, docs/UserGuide.md, repo-config.csv, src/functional/java/reposense/Entry.java, src/functional/resources/author-config.csv, src/functional/resources/repo-config.csv, src/main/java/reposense/RepoSense.java, src/main/java/reposense/model/Author.java, src/main/java/reposense/model/ConfigCliArguments.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/model/StandaloneAuthor.java, src/main/java/reposense/parser/ArgsParser.java, src/main/java/reposense/parser/AuthorConfigCsvParser.java, src/main/java/reposense/parser/ConfigFolderArgumentType.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/parser/RepoConfigCsvParser.java, src/test/java/reposense/parser/ArgsParserTest.java, src/test/resources/cli_location_test/author-config.csv, src/test/resources/cli_location_test/repo-config.csv
Part of #245 
```
RepoSense uses a CSV config file for all repository information.
Following #234, analysis can be done at author level.
To make author level analysis available to the users, the CSV config
file has to be broken down into repo-config.csv and author-config.csv.
Let's split the CSV config file to repo-config.csv and author-config.csv.
```
=> Split config csv file to repo-config.csv and author-config.csv #245

src/main/java/reposense/parser/AuthorConfigCsvParser.java
```
AuthorConfigCsvParser#getRepoConfiguration should return existing
RepoConfiguration from a list of RepoConfigurations. Otherwise it adds
a newly created RepoConfigurtion into the list and returns it.
However, due to a bug, any RepoConfigurations existing or not are added
to the list of RepoConfigurations causing duplicates.
Let's only add newly created RepoConfigurtion to the list to prevent
duplications.
```
=> Fix duplicate authors in underlying RepoConfig

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/api.js
Fix #226 
To view the repository, we need to manually open the link to navigate to it.
Let's simplify this by adding a redirect link to the remote repository in the 
dashboard itself.
=> Add clickable link to repository #226

frontend/src/index.jade
```
Authorship tab currently lacks a empty state, which might be confusing
for users since they are unsure if the information is being loaded or
there is nothing to show.
Let's add a default empty state for the authorship tab.
```
Added by Eugene:
To preview this change, go to the repo `reposense_testrepo-Delta_master` open code view for `Cod`
=> Dashboard: add indication to empty state in code view

frontend/src/static/js/v_authorship.js
fixes #267 
```
Currently, the authorship data is cached in the `window.REPOS` to
reduce unnecessary loading because `authorship.json` is a very big
file. However, this causes the the browser memory keep increasing as a
user keeps going through code of various authors.
Let's limit the cache of code view data to a fixed number of authors to
5.
``
=> Reduce memory cache in code view #267

src/main/java/reposense/authorship/FileInfoExtractor.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java
Fixes #299 
```
FileInfoExtractor#getFilePathFromDiffPattern(String) checks
for the group pattern '+++ b/path/to/file'
within the git diff result in order to get the file path.
However, when a file is renamed without changing any of its
content in between the commit range to analysis, the file will
appear in the git diff result, but since there are no lines to display,
the above group does not get printed, thus 
FileInfoExtractor#getFilePathFromDiffPattern(String) is unable
to match the pattern, causing the program to crash.
Let's add a check to skip these renamed but untouched files in 
the git diff result, since an untouched file has no lines to 
attribute any contribution.
```
=> error matching file path pattern inside file diff result #299

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_authorship.js
Fix #36 
```
Files in code view are shown in open state by default.
With the addition of #282, it can be useful to show only the file
headers as it provides a rough impression of the author's focus area
of contribution and pattern.
Let's add controls to allow user to expand or collapse all the files in
code view at their will.
```
=> Code view: add controls to expand/collapse all files #36

frontend/src/static/css/style.scss
Fix #311 
```
Untouched code uses the same background and font color as written
code.
This allows the possibility of it being passed off as written code
(i.e., give the viewer an impression that the author changed more code
than she actually did) because the only way to differentiate the two
types of code is the color of the line in the gutter.
Let's differentiate the two code types more by adding a light green 
background to written code.
```
=> code view: differentiate untouched code more #311

README.md
```
Documentation link in landing page points to the User Guide in
production.
This can result in users reading the User Guide that is ahead of
release, looking at features irrelevant to the jar they are using.
As users may not how to look for user guide pertaining to their
downloaded version, let's have the url in README to redirect user to
the latest released User Guide.
=> README: update url to UserGuide

docs/UserGuide.md
Fix #328 
```
Some fields in our CLI arguments and configuration files accept
multiple values.
This information was not delivered to the users and users have to infer
this from the given examples.
Let's deliver this concept more explicitly by adding foot notes to
provide the explanation for these fields.
```
=>  UserGuide: add instruction for multi-values fields and columns

docs/UserGuide.md, src/main/java/reposense/git/GitShortlog.java, src/main/java/reposense/system/CommandRunner.java, src/systemtest/resources/dateRange/expected/reposense_testrepo-Alpha_master/commits.json, src/test/java/reposense/git/GitShortlogTest.java, src/test/java/reposense/system/CommandRunnerTest.java
Fixes #341 
```
When no author details is specified for a repo to analyze, all authors who
have contributed to the repo will be analyzed by default, even if a date
range is specified where some of the authors did not contribute in.
As users are only interested in the analysis within that date range if they
specify one, having all the other authors who did not contribute in that
date range also listed out will lead to unnecessary usage of time generating
the report, and fill the dashboard with unnecessary information as those authors
will have zero contribution, increasing its memory usage.
Let's update the analysis to only consider the authors within date range
if no author details is specified.
```
=> If author info is not specified, show only those who contributed during analysis period #341

src/main/java/reposense/parser/OutputFolderArgumentType.java, src/test/java/reposense/parser/ArgsParserTest.java
Fixes #345
```
If the output path specified by the user does not exist, the program
exits with a 'folder not found' error message.
Let's automatically create the output folder for such cases
as it is more convenient to the user and is the norm in most software.
```
=> -output param does not allow nonexistent folder #345

frontend/src/static/js/v_summary.js
Fix #354 
```
When the granularity is set to week in report, the url link is still
using a single day time gap.
This should be updated accordingly to show users the commits that were
done in the week.
Let's update the url function to do a conditional check prior to the
generation of hyper link.
```
=>  granularity#week: fix url not using correct time gap #354

src/main/java/reposense/system/CommandRunner.java, src/test/java/reposense/system/CommandRunnerTest.java
Fix #363 
```
CommitInfoExtractor uses git log to extract users' commits info.
However, by default, the author matching pattern used in git log is
case sensitive.
This can cause the CommitInfoAnalyzer to miss out some or all their
commits in the analysis. As a result, some authors do not have any
ramps shown in their ramp chart, even though their code view shows line
contributions.
To resolve this problem, let's set the git log regex patterns to be
case insensitive.
```
=> Make the commits info analysis case insensitive #363

src/main/java/reposense/authorship/FileInfoExtractor.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/util/TestUtil.java, src/test/resources/FileInfoExtractorTest/windows:Illegal?Characters!File(Name).txt
Fixes #370 
```
Windows disallows certain characters for the file names, such as `/\:*?"<>|`,
while other OSes like Linux allows almost any characters for their file names.
This may result in some files with such `banned` characters in the repository
to not be copied/cloned into a local copy for Windows OS.
As we use the `git diff` command to find file differences for analyzing
repositories with a date range, such files with `banned` characters may appear
in the `git diff` result, which result in an InvalidPathException being thrown
when we try to create a Path to this file name, which is invalid in Windows.
This causes the program to crash as the exception is not handled anywhere.
Let's update FileInfoExtractor to handle files with invalid file names by
skipping those files.
```
=> InvalidPathException thrown during run time due to Illegal char <:> in file name #370

docs/UserGuide.md, src/main/java/reposense/git/GitDownloader.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/parser/AuthorConfigCsvParser.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/parser/RepoConfigCsvParser.java, src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/system/CommandRunner.java, src/systemtest/resources/author-config.csv, src/systemtest/resources/repo-config.csv, src/test/java/reposense/git/GitCheckerTest.java, src/test/java/reposense/parser/CsvParserTest.java, src/test/java/reposense/system/CommandRunnerTest.java, src/test/resources/cli_location_test/repo-config.csv, src/test/resources/repoconfig_empty_branch_test/author-config.csv, src/test/resources/repoconfig_empty_branch_test/repo-config.csv
Fixes #323 
```
Make branch an optional field.
Checking out to master is a redundant step as it doesn't guarantee that 
we are analysing the current working branch.
Let's,
* Remove branch as a mandatory field when parsing a CSV file
* Set default branch as HEAD
* Retrieve name of current working branch
* Update system and unit tests
* Update User Guide
```
=> Make branch an optional field #323

frontend/src/index.jade
Fixes #362 
```
Tooltip shows only total contribution.
Let's include the analysis period for the total contribution in the
tooltip to make it more user-friendly.
```
=> Show analysis period in contribution bar tooltip #362

frontend/src/index.jade
Fixes #386 
```
With the addition of #372, code view now shows the total LoCs
contribution too.
However this has caused a deficit in information as compared to the
summary view due to the absence of the date range.
To restore balance of the information, let's add the analysis period in
the code view too.
```
=> Show analysis period for total contribution in code panel #386

frontend/src/index.jade, frontend/src/static/js/main.js
Fixes #376 
```
Code panel shows both Expand and Collapse buttons.
This is not consistent with how expand/collapse buttons normally work.
Let's make it a single link and only display the Expand or Collapse
button, whichever one is relevant.
```
=> Code panel: make the expand/collapse button a toggle button #376

src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/report/ReportGenerator.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/parser/RepoConfigurationTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fix #395 
```
Standalone config goes through validation check before being utilized
for analysis. In the event where standalone configs contain invalid
value(s), RepoSense will indicate it by throwing an
IllegalArgumentException.
However, in #395, a standalone config with invalid `ignoreCommitList`
was found in one of the repositories which has caused an intermediate
crash during the analysis. This is due to the IllegalArgumentException
not being properly handled.
Let's handle the IllegalArgumentException by ignoring the standalone
config, also, ensure that none of the fields prior to validation.
```
EDIT: invalid config.json file added to testrepo-Alpha.
=> Fix unhandled IllegalArgumentException in RepoConfiguration#update #395

src/main/java/reposense/report/ReportGenerator.java
Temporarily fix for #391 #398 #399  
```
Due to the nature of our application, and the lack of simpler
alternatives, our application heavily relies on the external command
line utility, `git`. To make use of the tool, we employed a
CommandRunner class which starts a separate process to execute various
operations.
This, however, encourages the outbreak of RuntimeException as numerous
factors can cause `git` to return a non-zero status code and
CommandRunner allows these exceptions to go unchecked.
To prevent RuntimeException from interrupting the analysis of multiple
repos, let's skip the repo under analysis whenever a RunTimeException
occurs.
```
=> Hotfix for recent outburst of RuntimeException

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_authorship.js
Fixes #385 
```
With the addition of #372 and #388 , code view now shows the total LoCs
contribution and analysis period.
However, this does not provide any information on the LoC for each individual filetype. 
Let's show a breakdown of total contribution by filetype in the code view, and sort the file type displayed alphabetically to ensure that a certain file type always appears at the same place, giving predictability to the viewer.
```
=> Show breakdown of file type for total contribution in code panel #385

package.json
```
seems like after the recent update on the spuild library, the npmRunSpuild
task in gradle is not working the same as before.
Let's fix the version of spuild to use for the rendering of the dashboard.
```
=> Gradle task npmRunSpuild is not working as intended #409

src/test/java/reposense/git/GitLogTest.java
Part of #452
GitLogTest#gitLog_sinceDateInFuture_noContent() test method has a check
which asserts that if the until date given is before any of the
repository's commit date, the git log command should not give any
commmit info.
However, after the new year in year 2019, the test now fails. This may
be due to the Year 2038[1] problem. As the given until date is too
early (year 1950), this causes the time difference to overflow. As
such, a future until date is formed instead, causing git log to give
all the commit info, thus the test fails.
As a hotfix for this issue, let's set an earlier until date
(year 2010) for the test instead.
As this check is also not within the scope of the test method,
gitLog_sinceDateInFuture_noContent(), let's refactor it out to
a different test method, …
=> [#452] GitLogTest failure 

frontend/src/static/js/v_summary.js
Fix #471 
```
The link on ramps are broken; the organization and repository name on
the url links are undefined.
This is due the change in #425 where we encapsulate the names in
another layer of abstraction.
Let's fix the property accessors in v_summary.js to restore the broken
hyperlink.
```
=> Fix broken link on ramps #471

frontend/src/index.jade
Fixes #473 
```
When a file extension is unselected, the file content is not always updated 
despite a change in filename.
This is due to vuejs reusing the DOM for each file as a performance optimization. 
Let's add a key attribute to each file, so that vuejs can track every file correctly 
with proper reusing of the DOM. 
```
=> Fix mismatch of file content #473

docs/UserGuide.md, frontend/src/static/js/v_summary.js, src/main/java/reposense/model/Format.java
Fixes #474 
Some of the files committed are of .txt extension. In order to be able to track these files, let's add this as one of the default format.
=> Format and UserDoc: Add 'txt' format to default formats.

src/main/java/reposense/git/GitRevList.java
Fix #399 
```
When a file with the same name as the analyzing branch exist in the
repo, an uncaught RuntimeException will occur due to ambiguous argument
in git rev-list causing RepoSense to crash.
Let's add the `--` revision-path separator in `git rev-list` command to
distinguish the branch name from the ambiguous argument.
=> Fix RuntimeException due to ambiguous argument in git rev-list #399

frontend/src/index.jade, frontend/src/static/js/main.js
Fixes #464 
```
Code view is hidden upon initial loading of report.
Let's open the code view for the author at the top of the ramp chart
upon loading to provide a more representative view of the report,
especially for a user seeing a RepoSense report for the first time.
```
=> Open dashboard with code-view shown

frontend/src/index.jade, frontend/src/static/js/v_authorship.js
Fixes #534 
In #490, the `toggleNext()` are edited to limit the toggle option to the path of the title.
However, the untouched code button also uses this function. So this button does not work after #390 is merged.
Let's return the `toggleNext()` to its original state, but edit the way to call this function.
=> [#534] Fixes untouched code button failure

.travis.yml
```
In the Travis config file, we specify our Linux environment to use
JDK9 with `jdk: oraclejdk9` and `addons.apt.packages key`, but the
latter is redundant. Similarly, the command used to install frontend npm
dependencies can be simpified. The cd command does not change the
install location of the npm dependencies as frontend folder does not
contain a package.json file.
Let's remove the redundant commands for clarity and maintainability.
```
=> Remove redundant commands in Travis config

build.gradle
Fixes #537 
```
We use `./gradlew run` in development to conveniently run RepoSense
without the need to build a Jar.
It is expected to do the following tasks sequentially:
[a] npmRunSpuild - build frontend/src to frontend/build
[b] zipReport    - zip `frontend/build` to resource of zip
[c] build   	 - build src to build files
[d] run          - execute the build files
We can use `./gradlew run --dry-run` to list the running order.
Actual order:
:compileJava		[c]
:processResources 	[c]
:classes 	        [c]
:downloadNode 		[a]
:npmInstall 		[a]
:npmRunSpuild 		[a]
:zipReport 	        [b]
:run 			[d]
Expected order:
:downloadNode		[a]
:npmInstall		[a]
:npmRunSpuild		[a]
:zipReport		[b]
:compileJava		[c]
:processResources	[c]
:classes		[c]
:run 			[d]
The incorrect order may result in …
```
=> build.gradle: fix files compilation order

.travis.yml, appveyor.yml
```
RepoSense is advertised to run on JDK 1.8.0_60 and later.
However, we use JDK 9 in our CIs.
Let's downgrade to use JDK 8 in CIs to validate this non-functional
requirement.
```
=> Downgrade to JDK8 in CIs

docs/UserGuide.md
Fixes #546 
```
In the UserGuide FAQ section, we mention that commit contribution
may not appear in the ramp chart if the user did not associate the
correct author name aliases to their GitHub ID, and to double check
their author name aliases.
After #493 though, RepoSense allows user to associate their GitHub
email to their GitHub ID as well, which is more accurate as it is a
fixed value, compared to author name aliases which can have many
different values depending on their local git settings and on different
machines. As such, it is better to ask users to use email instead of
author name aliases if they face such problems of their contribution
not being tracked by RepoSense.
Let's update FAQ to propose email as an alternative to associate to the
user's GitHub ID instead.
The command …
```
=> FAQ: add another entry to propose email as alternative to GitHub ID #546

frontend/src/static/js/v_summary.js
```
Currently, the ramp chart's filter is updated when the checks have
passed. The checks only accounts for cases where the dates are valid,
checking that they are within range. When dates such as "2019-02-31" is
given, the filter is updated anyways. This causes the ramp charts to be
generated up till the repository's latest commit.
Let's add an additional check to ensure that a valid temporary date is
given before we update the filter fields.
```
=> Non-linear ramp chart cause by invalid date range #585

src/main/java/reposense/RepoSense.java, src/main/java/reposense/parser/ArgsParser.java, src/systemtest/java/reposense/ConfigSystemTest.java, src/test/java/reposense/parser/ArgsParserTest.java, src/test/java/reposense/parser/CsvParserTest.java, src/test/java/reposense/parser/RepoConfigurationTest.java
Fix #587 
```
Some of the messages used in RepoSense are structurally unoriented.
This include the missing transition message where --config flag is
unused, using default path for analysis and the double printing of
the help message, and the confusing arrangement of usage parameters as
shown in #587.
Let's fix these scenarios to improve the quality of our output messages.
```
=> Fix unoriented output messages

frontend/cypress/cypress.json
Fixes #584 
```
By default, Cypress use 4000ms as the timeout value for DOM-based
commands.
However, using the default timeout value may result in frontend test
failing, when the CI is experiencing heavier load.
Let's increase the timeout value to 30000ms.
```
=> Cypress: front-end test failing due to timeouts

.travis.yml, README.md, build.gradle
Fixes #600 
We do not have a Coverage Test because our coverage was low and 
had quite a few architecture changes in the past.
Having a coverage test allows us to improve our testing with higher 
revenue and lower costs.
Let's integrate Coverage Test using Gradle Jacoco plugin and codecov.io.
Meanwhile, build.gradle do not have a consistent line indentation and a 
consistent grouping of tasks and configures. Let's make all the lines to 
have an indentation of 4 and rearrange the tasks so they have a better
grouping.
=> [#600] Integrate Coverage Test

src/test/java/reposense/model/RepoConfigurationTest.java
`RepoConfigurationTest` is under package ` reposense.parser`.
The class tested is `RepoConfiguration` which is under package 
`reposense.model`. It is not reasonable to put this test under a
different package.
Let's move `RepoConfigurationTest` to `reposense.model` to 
solve the problem.
=> RepoConfigurationTest: move to reposense.model

.travis.yml
Fixes #648 
```
The oracle-java8-installer in our .travis.yml refers to
ppa:webupd8team/java repository. According to the repo maintainer [1],
the repository has been discontinued due to "licensing issues".
Similarly, the homebrew java8 [2] has been removed as well.
Let's use openjdk8 instead.
[1]: https://launchpad.net/~webupd8team/+archive/ubuntu/java
[2]: https://www.chuchur.com/article/mac-install-and-uninstall-java-jdk
```
=> .travis.yml: change oraclejdk8 to openjdk8

frontend/src/index.jade
```
Search bar component is not displaying the value that is provided 
by the URL parameter.
This confuses users into thinking that only the listed authors and 
repos are all that's captured by the system, when there are others 
which are filtered out.
Let's fix this bug by adding a two-way binding that binds the search 
field and the corresponding JavaScript filterSearch variable.
```
Fixes #667
=> [#667] Report: fix search bar not displaying value provided by url parameter

frontend/src/static/js/v_summary.js
Fixes #672 
```
The default value of granularity is `Day`.
`Commit` as granularity is more closer to reality because users are more likely to 
observe per commits rather than per day/week. Users can choose a more 
summarized view at their discretion.
Let's change the default value for granularity to `Commit`.
```
=> [#672] Toolbar: set 'commit' as default for granularity

frontend/src/index.jade
Fixes #699 
```
When summary charts are grouped by none or repo/branch, author name shows 
only the display name. Whereas when grouped by author, author name shows the 
display name as well as GitHub username.
This causes inconsistency in the author names. Furthermore, user won't be able to 
refer to the author's GitHub username when the summary charts are grouped by 
none or repo/branch.
Let's ensure the consistency of author names by making the format of author 
name as [display name] ([github username]).
```
=> [#699] Ensure author name consistency

frontend/src/index.jade, frontend/src/static/css/style.scss, frontend/src/static/js/v_authorship.js
Fixes #635 
```
The code view displays only the code without the line number.
It is hard to associate a specific line from the code view with the
actual code without the line number.
Let's update the code view to display the line numbers by adding an
array in each segment to keep track of the line numbers of the code.
```
=> [#635] CodeView: add line number to code

frontend/src/static/js/v_summary.js
```
Pressing the "X" button in the date field only clears the 
date, with no useful functionality.
Users who wish to go back to the default dates will 
need to manually pick the dates from the date picker,
which can be troublesome.
Let's reset the "since date" and "until date" to the earliest and 
latest date respectively, should the user clear the date in the 
respective boxes.
```
Resolves #695
=> [#695] Report: allow reset of date controls

docs/PublishingGuide.md
Fixes #606 
```
In the publishing guide, instructions were given to generate personal
access token to grant write-access to RepoSense for publishing.
Despite ease of setup, personal access token may not be as secure as it
can access all other repositories owned by the user.
Let's also support deploy key for enhanced security, which enables user
to grant access to only a single repository.
```
PR for deploy script at https://github.com/reposense/publish-RepoSense/pull/5
=> [#606] Enable use of deploy key for publishing

docs/UserGuide.md, src/main/java/reposense/parser/SinceDateArgumentType.java, src/systemtest/java/reposense/ConfigSystemTest.java
```
Following #690, asterisk is used in since date argument as a shorthand
to the date of the first commit.
As asterisk is also a reserved character in shell, using it without
escaping cause the program to be unusable.
Let's change the shorthand to d1 so it can be used directly without the
need to escape.
```
Fixes #781
=> [#781] Fix broken program when reserved character is used without escaping

build.gradle, src/main/java/reposense/system/CustomLogFormatter.java
Part of #705: making error messages more obvious in console output.
```
It is difficult to distinguish `Level.WARNING` and `Level.SEVERE`
log messages from the rest of the log messages in the console.
Users may miss out these important messages.
Let's make these messages more distinct by inserting a highlighted
`[ERROR]` status before the message.
```
=> [#705] Log: distinct warning and error messages

frontend/src/static/css/style.scss
Fixes #791 
```
The css property of line number only overwrites the color property of 
classes 'hljs-number' and 'hljs-comment'. Others classes such as
'hljs-quote', 'hljs-name' and more are not overwritten.
This will cause the color property of certain line numbers to inherit 
from the hljs classes that are not overwritten.
Let's overwrite all hljs classes to ensure the color property of the 
line number to always be grey.
```
=> [#791] CodeView: bugfix for unexpected colors in line numbers

frontend/src/index.pug, frontend/src/static/css/style.scss
```
Within ChartView, ramp charts with error messages are blended together 
with the other ramp charts without error messages as they both have 
similar UI.
Let's modify the UI of ramp charts with error messages to use red color 
for their info message font to distinguish itself from other ramp 
charts without error messages.
```
**Updated UI**
group by repo:
group by author:
group by none:
=> ChartView: modify UI of placeholder for repositories with no author commits

frontend/src/static/css/style.scss
Fixes #811 
```
The 'closer' class designated for icons that toggle code segments
is absolutely positioned. Due its parent class, 'untouched', being 
in default static position, 'closer' is positioned relatively to the 
edges of the root containing block.
When scrolling through horizontally within each code segment, the 
toggle icons remains unchanged in their position in x-axis, hovering 
over the text in code view.
Let's relatively position the 'untouched' class, which turns the class 
into a containing block. This ensures absolutely positioned elements 
contained within will be positioned relative to the edges of 'untouched'
rather than the root containing block. 
```
=> [#811] Fix position of toggle icons

build.gradle
Fixes #820 
```
The current arguments used to generate the sample report used in Cypress 
tests is '--repo https://github.com/reposense/RepoSense.git --view'. 
Since sinceDate and untilDate is not provided in the arguments, the 
report duration will be from one month before today's date until today's 
date. This causes the current sample report used for Cypress tests 
to contain empty ramp charts, which does not mimic a realistic report.
Let's add a '--since d1' argument to the existing arguments, which 
generates a more realistic sample report that contains the commits
made from start until today's date.
```
=> [#820] Update sample report used in Cypress tests

frontend/src/static/js/v_summary.js
Fixes #828 
```
PR #800 was intended to ensure the getFiltered() method to be executed 
only once when the page is reloaded. The solution used was to set 
boolean canGetFiltered to true in beforeUpdate() lifecycle hook, 
preventing the execution of getFiltered() before the lifecycle hook.
However, the beforeUpdate() lifecycle hook will only be executed when 
there are changes to the DOM. 
Instances where the page is reloaded and there are no changes to the DOM
will not set boolean canGetFiltered to true, preventing getFiltered() to 
be executed until the DOM has changed.
Let's revert PR #800 to allow getFiltered() to be executed even when 
there are no changes to the DOM.
```
=> [#828] Revert PR #800

build.gradle
```
One of our indirect dependencies, sass@1.22.8, requires
`url.pathToFileURL` which is only available in node.js 10.12.0 or
later.
As our version of node.js is at 10.5.0, this cause our CIs to fail.
Let's update node.js to the latest lts release 10.16.0.
```
Fixes #833
=> [#833] build.gradle: update node.js to 10.16.0

frontend/src/static/js/main.js, frontend/src/static/js/v_summary.js, frontend/src/static/js/v_zoom.js
Fixes #846 
```
Clicking on show ramp chart for this period button in the commits
panel calls updateDateRange(), which recomputes the duration of the
ramp chart according to the drags by the user. The method proceeds 
to call deactivateAllOverlays(), which removes the drags by the user.
Since no more drags are left after the first execution of 
updateDateRange(), clicking on the show ramp chart for this period
button will not be able to activate updateDateRange().
Let's use the zoom since date and until date to recompute the duration
of the ramp chart, instead of using the drags. This will ensure that
clicking on the button will always show the ramp chart for the 
designated period.
```
=> [#846] Fix bug of show ramps for this period button only works once

frontend/src/static/js/v_summary.js
Fixes #842 
```
Ramp slices appear outside of the ramp charts in week granularity.
This is due to the implementation of splitCommitsWeek() does not take
into account when the duration between since date and until date is
less than one week. When the duration is less than a week, the
algorithm calculates commits up to the following Monday, even if they
are beyond the until date. Hence, it causes a distortion in the ui.
Let's revamp the logic within splitCommitsWeek to check, and trim any
commits beyond the until date.
```
=> [#842] Fix out of bound ramp slices

README.md, docs/Team.md
As more members join and leave us, it is about time for us to distinct
the active members so that users can easily seek help from us.
Let's move our team list to a new page to separate our active and past
members into different section. Also, let's include and update the
roles to accredit our senior members who have been helping out with
many of the work, including mentoring the newcomers.
=> AboutUs: update team members

frontend/src/static/js/v_summary.js
According to @damithc in the slack chat group:
> Yes, it should be display name, which we can control e.g., in this case, we have prefixed it with tutorial ID. The github username is a random string we cannot control. Sorting by it doesn't have much value.
```
The sort by author name implementation is according to the authors' 
GitHub usernames.
Github usernames are strings that users have no control over, 
an unconfigurable field.
Let's modify the sorting of author names to be according to the authors' 
display names.
```
=> Modify sort by author name to be according to authors' display names

author-config.csv, src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json, src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json, src/systemtest/resources/author-config.csv, src/systemtest/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json, src/systemtest/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json, src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json, src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
Fixes #185 
```
The names being used for the repositories are short.
Using this kind of too simple test cases can cause bugs to 
go unnoticed and also can cause the actual UI to look 
different from the UI we see in test cases.
Let's change the names to real use case names which 
we are more likely to see. We do this by adding long 
names, names with special characters and numbers, and a 
blank instead of a name.
This has been done this way to cover various equivalence
partitions of the test input.
```
=> [#185] Use realistic person names for test repos

frontend/src/index.pug
```
Breakdown by file types functionality is broken when grouping by NONE 
or by AUTHORS.
This is caused by a typo in a variable name that does not exist. As a 
result, the report is unable to populate the list of file types and 
users won't be able to view the breakdown of contribution by file type 
when grouping by NONE or by AUTHORS.
Let's fix the typo in the variable name.
```
=> Report: fix breakdown by file type

src/main/java/reposense/model/RepoConfiguration.java, src/test/java/reposense/git/GitRevParseTest.java
Fixes #886
```
Appveyor CI is failing due to GitRevParseTest which checks for
existence of master branch.
This is because the git rev-parse command in the failing test method
has been using the wrong directory; the reference should be using the
target repo's root. The test, however, uses the repo folder name (which
is parent of the target repo's root), causing the test to fail.
Lets fix the test to use the correct directory.
When not in the target repo's root, git tends to use the resources of
higher order repositories (if it is found). On AppVeyor, RepoSense has
always been cloned as a repository, which subsequently clones the
target repositories into one of its subfolders for analysis. Hence, the
issue has been kept hidden as the verification has been performed
against the RepoSense's …
```
=> [#886] Fix test causing Appveyor to fail

src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/util/FileUtil.java
Fixes #806, fixes #951 
```
ReportGenerator: Ensure the list of paths returned from
`generateReposReport` only contains JSON files that were successfully
generated.
The method `ReportGenerator#generateReposReport` returns a list of
paths to the JSON files that need to be zipped, but assumes
that these files already exist.
Let's return a Optional<Path> from `FileUtil#writeJsonFile` so that
callers of this method can determine whether a JSON file was
successfully generated.
This allows `generateReposReport` to only return paths to JSON files
that were successfully generated.
```
=> [#806, #951] ReportGenerator: return paths of generated files

frontend/src/static/js/v_summary.js
Fixes #980
```
Date in authorship can be modified using url, resulting in invalid
date range being input.
This can be fixed by adding a validation function for window hash.
Let's put a validation for the date parameter in url.
```
=> [#980] Date in url adapted without validation

src/test/java/reposense/authorship/FileInfoExtractorTest.java
Fixes #1009
```
Appveyor CI is current failing in all PRs as it is updated and now uses
Git 2.25 instead of Git 2.23.
As updated from Git v2.24, Git for windows would print error for illegal
file name and prevent it from adding into index. As in our test cases
we run the command `git checkout someInvalidName`, an exception is
expected to be thrown, and since we do not catch it, the test fail. 
Let's remove the 2 outdated test as the git command now handles
detection of invalid file name and throw exception at the very
beginning.
```
=> [#1009] Appveyor Failing: remove outdated tests

frontend/src/static/css/v_summary.scss
Fixes #1029 
```
Due to the regression of #1003, the css property 
'float: left' was left out in the contribution bar. When 
break down by file type is checked, the contribution 
bar for each file type occupies separate lines instead 
of continuous lines.
Let's add the css property 'float: left' back to the 
contribution bar.
```
=> [#1029] Add float left property to contribution bar

src/main/java/reposense/model/Author.java
Fixes #1032
```
Author: Fix error in copy constructor
The Author class has a constructor which accepts an existing Author
object and creates a copy. However, the constructor assigns the
list of author aliases of the copied instance to the `ignoreGlobList`
attribute of the new instance.
Let's fix this error so users of this copy constructor will not
face erroneous behaviour.
```
=> [#1032] Author: fix error in copy constructor

src/main/java/reposense/commits/CommitInfoAnalyzer.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/main/java/reposense/git/GitLog.java, src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
Fixes #1019 
```
Analyzing repo with empty commits causes CommitInfoAnalyzer 
to throw ArrayIndexOutOfBoundsException. This occurs in 
CommitInfoExtractor#parseGitLogResults, where info lines 
and stat lines are split based on the last index of the newline 
character "\n".
As empty commits have no stat lines, it leads to 
ArrayIndexOutOfBoundsException due to the use of new line 
separator.
Let's:
- use '|' character as the splitting point of 
info lines and stat lines, instead of the new line '\n' 
character. This will ensure that the ref name details
will always be within info lines instead of stat lines.
- add a check for the availability of the ref   
name before accessing it to prevent the exception. 
Additional Info: No stat lines occurs for commits that are 
empty (done by git …
```
=> [#1019] Handle commit info extraction for empty commits

_reposense/config.json
Fixes #1109 
```
The default configuration consists of authors that are no longer
active in committing code to RepoSense. The jade file format is
no longer used in RepoSense as it is replaced by pug file format.
Let's add a recent active author, as it may reveal potential bugs.
Let's replace jade to pug file format as well.
```
=> [#1109] Config.json: include active author and pug file format

frontend/src/static/js/v_summary.js
Fixes #1140 
```
Clicking on the show ramp chart in this period does not update 
the since and until date hashes, which leads to a different 
summary period after reloading the page.
This is due to the hasModifedSinceDate and hasModifiedUntilDate
not set to true when calling updateDateRange, which prevents
the since and until date hashes to be updated.
Let's set hasModifedSinceDate and hasModifiedUntilDate to be
true when updateDateRange is called.
```
=> [#1140] Update date hashes when updating date range

src/main/java/reposense/git/GitDiff.java, src/test/java/reposense/git/GitDiffTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #850 
```
Repos that contains git submodules are not handled properly and cannot
be analyzed.
This is due to the diff result including the submodule information.
Let set --ignore-submodules=all in the git diff command to ignore all
submodule information.
```
=> [#850] Ignore git submodules when analyzing repos

frontend/src/index.pug, frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js, frontend/src/static/js/v_summary.js, frontend/src/static/js/v_zoom.js, frontend/src/tabs/zoom.pug
Fixes #1145 
```
When sidebar needs to be refreshed, such as re-rendering the 
authorship tab and zoom tab, we set `isTabActive` to false first to 
trigger the redrawing process. To ensure that the child component 
gets the updated changes, we bind a unique key to the child 
component to trigger re-rendering.
The previous implementation is done in such a way because the 
child component fails to get the changes in `info` prop due to the 
way we update the `info`[1]. This causes the SideBar component 
to be completely re-rendered, instead of only updating the 
component based on the changes in `info`. If we are able to let the 
SideBar component catch the change of `info`, we can directly 
watch the property and update the data upon the `info` 
change.
Let's declare the `info` prop …
```
=> [#1145] SideBar: revamp display logic

frontend/src/static/js/v_authorship.js
Fix #1124
```
File with name starting with period will not have its detail displayed
on authorship panel.
This is due to the minimatch library used which by default will not
match name `a/**/b` with `a/.d/b`, unless dot is set. So the file is
filtered out from selected files.
Let's set the dot property to true to allow the file details to be
displayed properly.
```
=> [#1124] Authorship: file name starting with period not displayed

frontend/src/static/js/v_zoom.js, frontend/src/tabs/zoom.pug
Fixes #1201 
```
There are regressions caused by PR #779, where the zIsMerge and 
zFilterGroup properties are not used properly within zoom tab.
They are using isMergeGroup and filterGroupSelection instead.
Let's modify them to use zIsMerge and zFilterGroup instead, in this 
way the zoom tab will be using the correct property values.
```
=> [#1201] Fix regressions of PR #779

docs/DeveloperGuide.md, package.json
Fixes #1137 
Fixes #1138
```
Expand pug-lint glob and remove fix option in lint
The pug-lint command does not expand globs provided as arguments,
relying instead on bash wildcard expansion. This causes the pug-lint
command to fail on windows.
The main linting script was also written with the --fix option, which
can increase the build time for CI.
This may also cause auto-fixable errors to go undetected, although the
lint script has an extra ‘--' that causes --fix to be recognised as a
file.
Let’s manually expand the globs for the pug-lint command, moving it to
a separate script for brevity.
Let’s also remove the --fix option used by the main linting script,
and move it to a separate lintfix script.
At the same time, let’s introduce --fix for stylelint as well.
```
=> [#1137][#1138] Expand pug-lint glob and remove fix option in lint

frontend/src/static/css/v_authorship.scss, frontend/src/static/js/v_authorship.js, frontend/src/tabs/authorship.pug
Fixes #1081
Alleviates #202
```
Improve file collapsing in authorship view
The authorship tab relies on several dom querying methods to toggle
whether a file is collapsed from view.
This hurts the performance of file collapsing, and detracts from the
use of vue as RepoSense’s front-end framework, decreasing code
readability.
Let's refactor this to use a new variable in the file object instead,
allowing vue reactivity to take over this behaviour.
This also fixes a bug with files not staying collapsed after changing
the file filter [#1081].
With this change, we are able to conveniently display both the expand
and collapse all buttons at the same time. Let's do so as well.
Occasionally, a small number of files have a large number of line
contributions. This slows the initial loading time at …
```
=> [#202, #1081] Authorship: improve file collapsing mechanism

frontend/src/ramp.pug, frontend/src/static/js/v_ramp.js, frontend/src/static/js/v_zoom.js
```
Refactor ramp and zoom globals
The ramp and zoom components have some component specific methods and
variables that can be moved inside the component definition.
Let’s do so, encapsulating component logic within the component itself.
```
ps: Travis is passing but the status isn't being reported back, have tried rebuilding quite a few times
=> Refactor ramp and zoom globals

frontend/src/static/js/v_segment.js, frontend/src/tabs/segment.pug
```
Add auto scrolling when a segment is collapsed
When a segment is collapsed, the scroll position of the authorship view
remains at the same position.
This can cause the user to feel lost after collapsing the segment.
Let's implement auto scrolling for the segment collapse button.
If the top button is out of the user’s view, the authorship view will be
scrolled to the segment’s top.
```
=> Add auto scrolling when a segment is collapsed

src/main/java/reposense/commits/CommitInfoAnalyzer.java, src/main/java/reposense/commits/CommitInfoExtractor.java, src/test/java/reposense/commits/CommitInfoAnalyzerTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #1244 
```
When a filename contains special characters such as double quotes
or the backslash character \, git log will escape those characters and
surround the entire file name with double quotes.
CommitInfoAnalyzer is not handling these cases, which will lead to an
assertion error that fails the entire analysis.
Let's add the handling of such cases, removing the surrounded quotes
from the filenames, if available.
```
An example to show how Git Log displays files with special characters:
actual: `"READ\ME"` 
how git log displays:`"\"READ\\ME\""`
Reference to the failed analysis in [CS2103's travis build](https://travis-ci.org/github/nus-cs2103-AY1920S2/ip-dashboard/builds)
=> [#1244] Add handling of filenames wrapped in double quotes

frontend/src/static/css/v_authorship.scss, frontend/src/static/js/api.js, frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js, frontend/src/tabs/authorship.pug
Resolves #910 
```
Save authorship tab controls as hash parameters
The filter and sorting options for the authorship tab are not persisted
across page reloads.
This results having to re-select the options whenever the page is
reloaded, leading to a less pleasant user experience.
Let's save the options for these controls as hash parameters, and use
them across page reloads when available.
```
=> [#910] Save authorship tab controls as hash parameters

frontend/src/index.pug, frontend/src/static/js/main.js, frontend/src/summary.pug, frontend/src/summary_charts.pug, frontend/src/tabs/authorship.pug, frontend/src/tabs/segment.pug, frontend/src/tabs/zoom.pug
Fixes #1178 and  #1191.
```
When grouped by repo, the same icon to link to the repo is duplicated
multiple times for no reason. Also, the icon to link to the author's
profile is hard to find.
We can make the links more intuitive and consistent by putting links to
the author's profile beside author names, and links to repo beside repo
names.
Let's reorder the icon group such that the hyperlinks are closer to the
respective names, as well as always showing the icons beside their
respective names. As this change heavily relies on the icons being
responsive, let's resolve issue #1191 as well to make use of
vue-fontawesome to make the icons responsive.
```
Note that there are some existing bugs that affect this PR.
1. Affected by #1185, but should work with the previews as the `config.json` is …
=> [#1178] Make github profile and repo hyperlinks more consistent

frontend/src/summary_charts.pug
Fixes #1249
```
View code icon shows when group by authors and merge group is
selected.
However, the functionality is not implemented yet. Clicking on the
icon shows garbage results.
Let's remove the icon when group by authors and merge group is selected.
```
=> [#1249] Disable view code icon when merge group and group by authors

src/test/java/reposense/git/GitLsTreeTest.java
Fixes #1163 
```
When RepoSense is run on Windows OS, it uses the 'validateFilePaths' 
method of the GitLsTree class to verify  if all the file paths in 
the repo are valid file paths on Windows OS.
Within unix_cloneInvalidWindowsFilePaths_success test case, it 
checks whether 'validateFilePaths' method runs correctly on 
non Windows OS. However, this test does not actually call
the `validateFilePaths` method.
Let's call 'validateFilePaths' in the test case, so we can 
confirm that the method works correctly on non Windows OS.
```
=> [#1163] GitLsTreeTest: Improve unix_cloneInvalidWindowsFilePaths_success

frontend/src/static/css/panels.scss, frontend/src/static/css/v_authorship.scss, frontend/src/static/css/v_zoom.scss, frontend/src/tabs/authorship.pug, frontend/src/tabs/zoom.pug
Fixes https://github.com/reposense/RepoSense/issues/1230
```
Currently the `show all commit messages` link on the zoom view displays
even when there is no messages available to show. 
This may cause confusion to the user because clicking on the link gives
no effect.
Let's hide the link when there are no available messages to show.
```
=> [#1230] Hide show all commit messages link when no messages available

docs/about.md, docs/contact.md, docs/dg/architecture.md, docs/dg/index.md, docs/dg/projectManagement.md, docs/dg/report.md, docs/dg/settingUp.md, docs/dg/styleGuides.md, docs/dg/workflow.md, docs/index.md, docs/showcase.md, docs/ug/cli.md, docs/ug/configFiles.md, docs/ug/customizingReports.md, docs/ug/faq.md, docs/ug/generatingReports.md, docs/ug/index.md, docs/ug/runSh.md, docs/ug/sharingReports.md, docs/ug/troubleshooting.md, docs/ug/usingAuthorTags.md, docs/ug/usingReports.md, docs/ug/withGithubActions.md, docs/ug/withNetlify.md, docs/ug/withTravis.md
Fixes #1290 and few other similar inconsistencies
```
The page title and the main heading of a page is exactly the same.
Let's use a MarkBind variable to hold that value so that it can be
specified only once and used in both as title and heading.
At the same time, let's fix some inconsistencies between page titles
and headings that were partially caused by the duplication this
commit addresses.
Warning: Two pages (runSh.md, usingAuthorTags.md) do not use
{{ title }} inside the <frontmatter>. This is due to a flaw in the
current MarkBind processor that affects variable values that
have `.` and `@` in them. This flaw has been fixed in the next
upcoming MarkBind release. Those two pages need to be 
updated after that version of MarkBind has been released.
```
=> Use variables for page titles and headings to reduce duplication

docs/_markbind/navigation/dgSiteNav.md, docs/_markbind/navigation/ugSiteNav.md, docs/index.md, docs/scripts/macros.njk
```
<include>ing the (ug|dg)SiteNave.md in the landing page site-map avoids
duplication but prevents optimal use of siteNav as well as site-map.
For example, we cannot use `:expanded:` in the siteNav to make an item
collapsible because `:expanded:` appears as raw text in the landing page.
Let's use nunjucks to define siteNav items as an array and a macro to
render it optimally for both reuse contexts.
Pros:
* siteNav items are now collapsible
* landing page shows links as a hierarchy rather than a flat list
Cons:
* The code is more complicated than before: But, the complexity is
within the expertise of RepoSense developers as nunjucks code is
similar to JavaScript.
```
=> Use nunjucks to generate siteNavs and the site map

docs/_markbind/navigation/dgSiteNav.md, docs/_markbind/navigation/ugSiteNav.md
```
UG/DG: Fix the current item in the siteNav not being marked
The site navigation menu of the UG and DG does not highlight the
currently loaded page in blue, as it is supposed to.
The reason is, the {{baseUrl}} variable used in the macro does not
get imported with the macro. The links generated still work because
the baseUrl is empty in this case. But they don't get highlighted due
to some strictness in how MarkBind finds which item to highlight.
Let's fix it by adding `with context` to the nunjucks import statement.
```
=> UG/DG: Fix the current item in the siteNav not being marked

docs/ug/grantingWriteAccess.mbdf, docs/ug/withGithubActions.md, docs/ug/withNetlify.md, docs/ug/withTravis.md
I was initially trying to fix two broken links but ended up refining the rest of the steps as well.
```
UG: Tweak instructions for Netlify, Travis, GitHub Actions
Let's tweak the intsructions for working with Netlify, Travis, and
GitHub Actions in the following ways:
* Use 'Step N' tags for setting up instructions in all three.
* For the above, start each step with a bolded phrase that gives an
overview of the step.
* Remove links to admin-only pages because the reader does not have
access to those pages e.g., publish-RepoSense/settings/secrets etc.
* Show multi-part steps as multiple sub-steps.
```
Changes are in these pages:
* UG -> RepoSense with Netlify
* UG -> RepoSense with GitHub Actions
* UG -> RepoSense with Travis
=> UG: Tweak instructions for Netlify, Travis, GitHub Actions

build.gradle, gradle/wrapper/gradle-wrapper.properties, package.json
Fixes #1302 
```
The downloadNode Gradle extension is outdated, as a result of which
AppVeyor integration is failing. 
Let's update the Gradle version to keep up to date with its development.
From Gradle 5.0 onwards, the tasks running with code coverage are configured to 
delete the execution data just before they start executing another task. As a result of 
this, our code coverage dropped significantly since we use the same file to store the
execution data of the different tests. 
Let's use different files to store the execution data of the different tests to fix 
this problem. 
```
=> Update Gradle Version

frontend/src/static/js/v_authorship.js
Fixes #1193 
```
There are a few instances in the frontend code where we are comparing an author
name against the name "-" (which represents an unknown author). 
Let's place this comparison in a method such as isUnknownAuthor 
to improve readability
```
=> [#1193] Add helper method to replace direct comparison of git author name with '-'

src/main/java/reposense/model/AuthorConfiguration.java, src/main/java/reposense/model/RepoConfiguration.java
Fixes #1204 
The name of the method can be confusing because it appears like we are
wiping out the author list that was set on the previous line.
Let's,
* Break resetAuthorInformation method into two methods to increase
code readability.
=> [#1204] AuthorConfiguration#resetAuthorInformation can be made more readable

frontend/src/static/css/v_authorship.scss
```
The file type label is bold and this is inconsistent with other labels.
To standardize, let's set the font weight type of file type label to
normal.
```
Fixes #1251
=> [#1251] Change file type label font weight

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation.md
Fixes #1282 
```
There are warnings in travis logs regarding these trailing
whitespaces.
Let's remove them to tidy up the logs.
```
=> [#1282] Remove trailing whitespace in issue templates

src/main/java/reposense/model/RepoConfiguration.java
Fixes #938.
```
The Javadoc comment for the update method within RepoConfiguration 
does not mention that the update function will alter the repository 
level information.
Let's update that Javadoc comment to reflect its functionality.
```
=> [#938] Fix inaccurate Javadoc comment

frontend/src/index.pug
Fixes #1111.
```
The report does not specify a HTML doctype, which may cause the
webpage to go into quirks mode, depending on the browser.
Let's specify a HTML doctype to prevent it from happening.
```
=> [#1111] Specify HTML doctype for report

src/test/java/reposense/template/GitTestTemplate.java
Fixes #1128 
```
The setting of file format in the BeforeClass method of GitTestTemplate 
is not required for the cloning of the test repository.
Let's remove it to make it clear that this setting is not required for the tests.
```
=> [#1128] Remove setting of file format in BeforeClass method of GitTestTemplate

frontend/src/static/js/v_authorship.js
```
File type hashes in authorship tab were delimited with a
non-existent delimiter and this causes errors when restoring
selected file types from the hash.
Let's use an appropriate delimiter so that file type hashes 
can be parsed correctly. 
```
Fixes #1328
=> [#1328] Fix usage of non-existent delimiter

.travis.yml
Fixes #1312 
```
The markbind to gh pages deployment task is executed at every
pull request, which runs npm install but do not deploy to the
gh pages since it is not the master branch. This is unnecessary 
and takes up build time.
Let's ensure that the deployment task to not be run at all when it 
is not from the master branch.
```
=> [#1312] Conditional run for markbind to gh pages deployment

frontend/cypress/tests/zoomView/zoomView_reload.js, frontend/cypress/tests/zoomView/zoomView_selectFileTypes.js, frontend/src/static/css/panels.scss, frontend/src/static/css/v_authorship.scss, frontend/src/static/css/v_zoom.scss, frontend/src/static/js/v_summary.js, frontend/src/static/js/v_summary_charts.js, frontend/src/static/js/v_zoom.js, frontend/src/tabs/zoom.pug
Resolves #1239
```
With PR #1192, we have the file type info of each commit, 
but users are still unable to view the type of file changes 
made in each commit as this information is not displayed.
The addition of filetype tags in the commits panel gives 
users an easy view to the type of changes made in 
each commit.
Let's add file type tags to each commit in the 
commits panel along with an additional filtering 
functionality for easy viewing.
```
=> [#1239] Add filetype tags in commits panel

src/main/java/reposense/authorship/FileInfoAnalyzer.java, src/main/java/reposense/model/AuthorConfiguration.java, src/main/java/reposense/model/RepoConfiguration.java, src/test/java/reposense/authorship/FileInfoExtractorTest.java, src/test/java/reposense/commits/CommitInfoAnalyzerTest.java, src/test/java/reposense/model/RepoConfigurationTest.java, src/test/java/reposense/parser/RepoConfigParserTest.java, src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #1207 
```authorEmailsAndAliasesMap``` is renamed to ```authorDetailsToAuthorMap```. 
This aims to better reflect the following structure within the mapping.
```
git id -> author
email -> author
alias -> author
```
=> [#1207] AuthorConfiguration: Rename authorEmailsAndAliasesMap to authorDetailsToAuthorMap

frontend/src/static/js/api.js
Fixes #1356 
**Current Situation**
Parameters were stored in `window.location.hash` which automatically adds the `#` symbol to the url. (Undesirable due to issues with copying non-alphabetical characters in some pdf applications).
**Outline of Solution**
Use `window.history.replaceState()` to edit the url directly to store parameters.
URL uses `?` to separate the path and parameters, and the symbol used can be easily modified in the future.
**Possible Alternative**
Using `window.history.pushState()` will instead leave the old url in the history (so one can navigate back to the previous url by using the back button on the browser. This does not rerender the page however.)
**Proposed commit message:**
```
Parameters were stored in `window.location.hash` which automatically adds the `#` …
```
=> [#1356] Not use # in URLs 

src/main/java/reposense/model/RepoLocation.java
Resolves #1233.
```
Within RepoLocation, a Git URL is checked using both regex and by
instantiating a java.net.URL object.
With a stronger regex, we can avoid having to instantiate a URL object.
Let's use the stronger regex to replace creating a URL object when
checking a Git URL.
```
Notes:
- The original issue suggests a regex of `^(http|https)://github.com/(?<org>.+?)/(?<repoName>.+?)\\.git$`. There are some minor deviations from this.
- The forward slashes `/` need to be escaped with `\\`, as done in the old regex.
- `(http|https)` has been replaced with a more elegant `https?` pattern
- Thus, the final regex to be used (as shown in the code) is `^https?:\\/\\/github.com\\/(?<org>.+?)\\/(?<repoName>.+?)\\.git$`
- The validation logic within `verifyLocation` ("line 69 - line 74") has …
=> [#1233] Use a more specific regex for URL validation

.travis.yml
Fixes #1374 
```
The deployment of pr docs are used with an outdated node version, 
which causes the building of markbind to fail.
Setting the node version to the latest version will fix the issue, 
as markbind requires node version >= v10.13.0 installed.
Let's specify the node version for the deployment to be `lts/*`, 
which will ensure that the markbind runs without errors.
```
=> Utilise latest node version in pr docs deployment

.github/.workflows/stale.yml
```
Few PRs are left open for a long time without any follow-up activity 
from the author of the PRs. This prevents other developers from 
taking up the issue and solving it. Therefore, the senior developers 
need to find such PRs manually and close them.
Let's automate the process of closing inactive PRs using GitHub Actions.
```
=> Github Actions - Close Stale Pull Requests

.github/workflows/integration.yml, .github/workflows/pending.yml, .github/workflows/surge.yml, config/gh-actions/deploy.sh
Fixes #1429.
```
Currently, GitHub Actions can encounter race conditions where
multiple pull requests are deployed at once, causing confusion as
to the exact artifacts to download. This is caused by not
specifying the pull request numbers when downloading artifacts.
Let's make it such that the correct artifacts are downloaded even
when multiple deployments occur concurrently.
```
Testing pull requests:
- https://github.com/dcshzj/RepoSense/pull/4
- https://github.com/dcshzj/RepoSense/pull/5
=> [#1429] Make GitHub Actions workflows more specific for artifacts

frontend/src/static/js/main.js, frontend/src/static/js/v_authorship.js, frontend/src/static/js/v_summary.js, frontend/src/static/js/v_zoom.js
```
window.decodeHash() is called several times throughout the code.
window.decodeHash() reads params from the url.
It does not make sense for window.decodeHash to be called 
any more than once per page reload.
Furthermore, I encountered an issue in projectify frontend
where window.encodeHash() is called 
before window.decodeHash()
Let's call window.decodeHash() only once in the entire code.
Let's call window.decodeHash() before window.encodeHash()
can possibly be called.
```
=> [#1424] Call `window.decodeHash` only once

frontend/src/static/js/utils/ramp_colour_generator.js, frontend/src/static/js/v_summary.js
Fixes #1468
Regression caused by #1421.
```
Repositories with more than 19 different types of files will crash,
which can be traced from line 448 of v_summary.js
Bug is caused by a function not being copied properly in #1421,
leading to an undefined function call.
Let's copy the function over properly.
```
=> [#1468] Dashboard loading empty if base URL is given

frontend/src/static/js/v_authorship.js, frontend/src/tabs/authorship.pug
Fixes #1446 
```
Restore display name on authorship panel after reloading
Currently, the display name of the author is not shown
after reloading the authorship panel.
Restoring the name will make the interface look more
consistent.
Let's enable the restoring of name after reloading.
```
=> [#1446] Restore the name on authorship panel after reloading

build.gradle, frontend/src/index.pug, frontend/src/static/js/v_authorship.js, frontend/src/static/js/v_zoom.js, package.json
```
browsersify and vueify is used solely to import minimatch.
Given that vueify is deprecated, and that it is used solely
to import minimatch in only v_authorship.js, it is better
to simply make minimatch work with the current 
implementation of imports by using a older version
of minimatch, as it is not critical to the functioning
of Reposense.
Lets remove browsersify and vueify.
```
There should not be any change to user experience.
=> Frontend: remove browsersify and vueify

frontend/src/static/js/v_authorship.js, frontend/src/static/js/v_zoom.js
Resolves #1485
```
Regression by #1390.
Currently zoom tab does not update properly if one of the
zoom watchables do not change.
Let's watch the tabZoomInfo stored in vuex instead of 
zoomOwnerWatchable.
This works as we ensure that every change to tabZoomInfo 
stored in vuex replaces tabZoomInfo with a new object. 
Hence watching the object pointer stored in tabZoomInfo 
is sufficient.
Everything here also applies to the authorship tab with
authorshipOwnerWatchable and tabAuthorshipInfo instead.
```
Changes in behavior:
Clicking on an already highlighted zoom/authorship tab icon on the summary chart will reset the tab even if there is no changes to summary chart.
=> [#1485] Watch tab info directly

frontend/src/index.pug, frontend/src/static/js/v_authorship.js, package.json
Regression by #1482,
```
minimatch@1.0.0 is deprecated and is causing some problems.
Lets upgrade to minimatch@3.0.4.
```
=> Upgrade minimatch version

src/main/java/reposense/parser/ArgsParser.java, src/main/java/reposense/parser/DateArgumentType.java, src/main/java/reposense/parser/PeriodArgumentType.java, src/main/java/reposense/parser/SinceDateArgumentType.java, src/main/java/reposense/parser/UntilDateArgumentType.java, src/main/java/reposense/util/TimeUtil.java, src/test/java/reposense/util/TestUtil.java, src/test/java/reposense/util/TimeUtilTest.java
Part of #634.
Part of #1360.
Part of #1501.
```
Many of the time-based functionality and logic are scattered
about in various files, which increases code duplication and is a
maintenance burden.
Let's abstract all time-based functionalities into the TimeUtil
class such that multiple places in the code can reuse the same
logic.
```
=> [#634] Extract time-based functionalities to TimeUtil

docs/ug/configFiles.md
Related to #1533 
```
Add link to glob syntax in the User Guide
The path glob syntax used in the Ignore Glob List
column of the CSV configuration files is currently not
documented for the user. This can cause issue when
an invalid path glob is used to generate the report.
Adding a link to the official documentation will make
it more convenient to the user.
Let's add the link to the glob syntax in the User Guide
```
=> Add link to path glob syntax in the User Guide

src/main/java/reposense/RepoSense.java, src/main/java/reposense/model/ConfigCliArguments.java, src/main/java/reposense/parser/ArgsParser.java
Part of #634.
Part of #1360.
Part of #1501.
```
The current design of getting the ReportConfiguration object in
the main RepoSense class is flawed and the design is not ideal,
as it meant that configuration has to be set and parsed twice.
Let's move the logic for getting the ReportConfiguration object
into ArgsParser to avoid having to duplicate configuration parsing
in the future.
```
=> [#634] Move logic for getting ReportConfiguration to ArgsParser

frontend/cypress/package-lock.json, frontend/cypress/package.json, frontend/cypress/tests/chartView/chartView_contributionBar.js, frontend/cypress/tests/zoomView/zoomView_selectFileTypes.js
Resolves #1519
```
Currently we are using Cypress major release version 3.
Cypress 3.8.3 was released in January 2020 and is using
outdated dependencies with security vulnerabilities.
The latest version of Cypress is 7.0.1.
Let's upgrade Cypress major release version to 7.
Upgrading to Cypress 7 has also caught some bugs in tests.
Let's fix those test bugs.
```
=> Upgrade cypress version to ^7.0.1

src/main/java/reposense/model/RepoLocation.java, src/test/java/reposense/model/RepoLocationTest.java
Resolves #1212 
```
RepoLocation: Remove redundant backslashes in regex
In RepoLocation.java, our current regex is 
"^https?:\\/\\/github.com\\/(?<org>.+?)\\/(?<repoName>.+?)\\.git$".
There is no need to escape the forward slash "/" character with the
"\\" characters, as the forward slash does not have a special meaning
when used on its own.
Let's remove the redundant backslashes and add more tests for
different types of repository URLs.
```
=> [#1212] RepoLocation: Remove redundant backslashes in regex

src/test/java/reposense/git/GitCloneTest.java, src/test/java/reposense/util/TimeUtilTest.java
Commit Message:
```
The current test code for RepoSense contains two methods that include
a redundant throws clause.
Let's remove both redundant throws clauses in GitCloneTest.java and
TimeUtilTest.java.
```
=> Test: remove redundant throws Exception clauses

build.gradle, src/main/java/reposense/git/GitCatFile.java, src/main/java/reposense/parser/CsvParser.java, src/main/java/reposense/system/CommandRunnerProcess.java, src/test/java/reposense/git/GitUtilTest.java, src/test/java/reposense/parser/AuthorConfigParserTest.java
Fixes some minor issues I found while working on other pull requests.
1. removed use of raw types
2.  add missing space from error message in `CommandRunnerProcess::waitForProcess()`
Commit Message:
```
Fix missing space and use of raw types
There are multiple occurrences of use of raw type within the code
which results in compilation warnings. Additionally, there is a 
missing space in one of the error messages.
Let's address these minor issues in the code.
```
=> Fix missing space and use of raw types

src/main/java/reposense/authorship/FileInfoExtractor.java
Fixes #1575 
A normal file path looks like `+++ b/file/path/` while a deleted file shows up as `+++ /dev/null/`
The current regex will instead parse out the string `dev/null` without the initial slash for deleted files and attempt to match it to `/dev/null/`.
This change has no direct impact on the output of the program at the moment as the relevant lines of code (linked below) has an additional `if` statement where the `dev/null` filepaths are discarded unintentionally. However, if there is a change in the program flow then it might become an issue in the future.
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L114-L121
```
Current regex expression matches dev/null/ while the …
```
=> [#1575] Fix misidentification of deleted files as edited files

frontend/cypress/tests/codeView/codeView_reload.js
Fixes failing Cypress test in ```codeView_reload.js``` which occurs after merging in [PR#1412](https://github.com/reposense/RepoSense/pull/1412)
Commit Message:
```
Fix failing Cypress test in codeView_reload.js
Cypress test in codeView.js is failing because the test analyzes
RepoSense's repository itself to run tests on. When PR#1412
was merged in, RepoSense no longer has any pug files whereas
the test case assumes pug files are still there thus leading to an
error. The selector utilized in the test refers to an input element
with id pug that no longer exists.
Let's change the selector in the test to refer to an input element
with id java that still exists in RepoSense's repository.
```
=> Cypress: replace nonexistent input element with pug id in selector in codeView_reload.js

docs/dg/workflow.md, frontend/.gitignore
Includes a feature added in #1412.
The gradle hot reload feature is only tested to be working for Windows (what I use to develop Reposense), not tested on Mac, and not working on Linux.
This is due to gradle needing to use OS specific commands to ensure that the website does not become an orphaned process with no way of killing it other than by pid.
Refer to https://github.com/srs/gradle-node-plugin/issues/238 for more information about the orphaned process problem
Users who can't run the gradlew version can just run `npm run serveOpen` in the frontend folder.
```
Frontend hot reload is a new feature added in #1412,
which will significantly help frontend developers.
Let's add it to to the documentation.
Let's also update the gitignore.
```
=> Include the frontend gradle hot reload feature in DG

.github/workflows/integration.yml
Fixes #1606.
The status checks has also been updated in the repository settings.
```
The Ubuntu 16.04 LTS runner for GitHub Actions is no longer supported
as at 16 October 2021. This is a breaking change that caused all
GitHub Actions checks to not complete.
The macOS 11 runner is also available for use now, and will be made
default on 13 December 2021.
Let's update the list of runners based on these changes.
```
=> [#1606] GitHub Actions: update list of runners

docs/dg/architecture.md, docs/dg/projectManagement.md
Fixes #1595.
```
There is currently no specific instruction on how to update the
release branch before making a release, or how to handle critical bugs
spotted after the release is made.
Adding these instructions will reduce the communication expenses in
the project release.
Let's adjust the release guide accordingly.
```
=> [#1595] Add release branch usage and hot patching instructions

frontend/src/views/v-zoom.vue
Fixes #1584 
Solution: Add a solid transparent border to prevent it from pushing the content around when visible.
```
Prevent commit message from shifting rightwards when clicked on.
Clicking on a commit pushes the message box rightwards, which can be
disorienting.
Let's add a solid transparent border to prevent it from pushing the 
content around when visible.
```
=> [#1584] Clicking on commit message causes it to shift slightly

frontend/src/views/v-zoom.vue
Fixes #1543 
**Summary**
Removes the "Show ramp chart for this period" anchor and `openSummary` method that only seems to be used by this feature. There does not appear to be deeper implementation for this feature beyond the above.
**Proposed commit message:**
```
The "Show ramp chart for this period" feature does not seem to be
particularly intuitive, and as discussed in #1543, may not be very
useful since users can do this manually. 
Let's remove this option from the front end and the associated 
`openSummary` method.
```
=> [#1543] Remove the "Show ramp chart for this period" feature

build.gradle
**Proposed commit message:**
```
The hotReloadFrontend gradle task does not support Linux. Apache
ant's `Os` class does not have an OS family specifically for Linux.
The Mac hot reload feature also does not appear to work.
Let's:
- add hot reload for Linux using gradle's OperatingSystem::isLinux
- use `npm run serveOpen` command for both Mac and Linux
```
Tested on Windows, Mac and Fedora Linux
=> Support frontend hot reload on Linux

frontend/src/components/v-summary-charts.vue
Fixes #1638 
**Proposed commit message:**
```
To calculate the number of contribution bars to display in 
getContributionBars, a parseInt of the ratio of a user's contribution
to the contribution limit is used. However, if the contribution is
much lower than average, the ratio is represented in scientific
notation and parseInt does not return the integer part of the number
(parseInt of 3.2301723943006836e-7 would return 3).
Let's use Math.floor to get the integer part of the contribution ratio 
instead of parseInt in getContributionBars, as is currently done in 
getFileTypeContributionBars.
```
Before:
After:
=> [#1638] Replace parseInt with Math.floor for contribution bars

frontend/cypress/support.js, frontend/cypress/tests/chartView/chartView_contributionBar.js, frontend/cypress/tests/chartView/chartView_errorSummary_messageBox.js, frontend/cypress/tests/chartView/chartView_filterBreakdown.js, frontend/cypress/tests/chartView/chartView_mergeGroup.js, frontend/cypress/tests/chartView/chartView_percentage.js, frontend/cypress/tests/chartView/chartView_reload.js, frontend/cypress/tests/chartView/chartView_toolBar_searchBox.js, frontend/cypress/tests/chartView/chartView_zoomFeature.js, frontend/cypress/tests/codeView/codeView.js, frontend/cypress/tests/codeView/codeView_checkFileTypes.js, frontend/cypress/tests/codeView/codeView_hideFileDetails.js, frontend/cypress/tests/codeView/codeView_load_benchmark.js, frontend/cypress/tests/codeView/codeView_reload.js, frontend/cypress/tests/codeView/codeView_switchAuthorship.js, frontend/cypress/tests/zoomView/zoomView_hideCommitMessages.js, frontend/cypress/tests/zoomView/zoomView_reload.js, frontend/cypress/tests/zoomView/zoomView_selectFileTypes.js, frontend/cypress/tests/zoomView/zoomView_switchZoom.js
Fixes #1540 
```
Cypress.wait() is placed at the start of every cypress test. However,
they do not serve any purpose other than to slow down the tests.
Let's remove them to speed up frontend testing.
```
=> [#1540] Remove Cypress.wait() at the start of cypress tests

docs/dg/report.md
```
In the developer documentation, report.md lists spuild as a dependency
even though it is no longer being used anywhere in the project.
Furthermore, some of the descriptions for how data is managed is
outdated.
Let's correct some of the outdated information in the documentation.
```
Additional information:
Every sequence diagram in `report.md` is wrong as no data actually passes through `app.vue`.
=> Docs: update documentation for frontend architecture

frontend/src/views/v-zoom.vue
Part of #1627.
```
beforeDestroy() is replaced by beforeUnmount() and it is not supported
in Vue 3.
Let's update the usages of beforeDestroy() and replace it with
beforeUnmount().
```
Details can be found [here](https://v3-migration.vuejs.org/migration-build.html#fully-compatible).
=> Frontend: remove deprecated beforeDestroy() syntax

frontend/src/components/v-ramp.vue
Part of #1627.
```
In Vue 2, when they exist on the same node, v-if has a lower priority
than v-for. However, this is the opposite in Vue 3.
Let's use the recommended filtered array to avoid ambiguity.
```
Details can be found [here](https://vuejs.org/guide/essentials/list.html#v-for-with-v-if).
=> Frontend: combine v-for and v-if

frontend/cypress/tests/codeView/codeView_switchAuthorship.js, frontend/src/views/v-authorship.vue
Needed for #1627
```
vue-fontawesome cannot be used directly in another component in Vue 3.
Cypress test is updated to ensure the correct element is fetched during
testing.
Let's move the condition check one level above to avoid this problem.
```
You can find the `vue-fontawesome` issue [here](https://github.com/FortAwesome/vue-fontawesome/issues/313).
=> Frontend: fix vue-fontawesome Vue 3 compatibility

frontend/cypress/tests/codeView/codeView_switchAuthorship.js
Part of #1736.
```
Due to the removal of the appveyor.yml file in #1731, the
codeView_switchAuthorship cypress test no longer works, as it expects
yml files to be present in the RepoSense repository.
Let's temporarily adjust the codeView_switchAuthorship cypress test so
that the frontend CI tests can pass, by removing the check on yml files.
In the longer term, the frontend tests' dependency on the RepoSense
repository should be removed, as it can make the CI tests unstable.
```
The yml file removed is the appveyor.yml file, which was removed in #1731. In the long term, CI tests should not be affected by changes to the RepoSense repository.
=> [#1736] Temporary adjust cypress test codeView_switchAuthorship

README.md, docs/dg/devOpsGuide.md, frontend/cypress/config/repo-config.csv, frontend/cypress/tests/codeView/codeView_switchAuthorship.js
Fixes #1738 
```
Cypress tests depend on RepoSense master which is constantly changing.
This can break tests as it did when #1731 was merged.
Let's use a separate branch 'cypress' in the RepoSense repository to
generate fixed reports for frontend tests that are not affected by
merges to master. Changes required for testing new frontend features
can be made to the cypress branch which will be independent of master.
Let's also remove the AppVeyor CI badge since we no longer use it as
of PR #1731.
```
=> [#1738] Remove dependence of Cypress tests on RepoSense master

src/main/java/reposense/RepoSense.java
Releases the `reposense.log.0` resource for writing logs.
```
Log resources are currently only fully released when the process exits.
This leads to the persistence of the reposense.log.0.lck lock file in
some scenarios.
Let's release the log file resource at the end of RepoSense execution.
```
Necessary for #1746 as the log file is not properly released during each test case and thus cannot be deleted while running the system tests. I'm not too sure how `ConfigSystemTest` gets around it but it does not seem to have the same problem deleting the report directories. The implementation between `ConfigSystemTest` is quite different as it does not make use of `RepoSense::main`.
Right now, I believe the issue can be seen when we run `gradlew run -Dargs="-r <some repo> -v"` and then Ctrl+C the …
=> Release Logger resources once RepoSense finishes processing

docs/ug/cli.md, src/main/java/reposense/commits/CommitResultAggregator.java, src/main/java/reposense/parser/ArgsParser.java, src/main/java/reposense/parser/SinceDateArgumentType.java, src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/util/TimeUtil.java, src/test/java/reposense/parser/ArgsParserTest.java
Fixes #1774.
Fixes #1778.
```
The use of Instant.ofEpochMilli(Long.MIN_VALUE) as the arbitrary first
commit date now fails shallow cloning for
testSinceBeginningDateRangeWithShallowCloning system test.
In addition, using this arbitrary date in convertToGitDateRangeArgs
when converting timezone results in an overflow causing sinceDate to
be greater than untilDate. Thus, no commit results are retrieved,
leading to failing system tests.
Also, the arbitrary first commit date is in UTC. However, in the
convertToGitDateRangeArgs method, the zoneId used for the conversion
is from the config, which may be different. This leads to an erroneous
timezone conversion.
Finally, using --since d1 with --period results in an unintended date
range because the --period and the arbitrary commit date from …
```
=> [#1774] Fix unintended behavior related to --since d1

config/checkstyle/checkstyle.xml
Part of #1769 
```
The oss-generic link for the coding standard is obsolete. At the same
time, the description vaguely refers to a module. The checkstyle file 
also references our own standards, which should be mentioned explicitly.
The JavadocType check actually checks that the Javadoc for classes,
enums and interfaces are of the correct format. The MissingJavadocType
check should be used instead to check that the public classes, enums and
interfaces have Javadoc.
Finally, the phrase "format's Javadoc" for the comment on the
JavadocMethod check does not make sense.
Let's change the coding standard link to the one used by SE-EDU, remove
the reference to the module and add the link to our style guide.
Let's also update the comments for the checks and add the
MissingJavadocType check.
```
=> Checkstyle: add MissingJavadocType check and update comments

src/main/java/reposense/RepoSense.java, src/main/java/reposense/authorship/FileInfoAnalyzer.java, src/main/java/reposense/authorship/FileInfoExtractor.java, src/main/java/reposense/commits/CommitInfoAnalyzer.java, src/main/java/reposense/commits/CommitResultAggregator.java, src/main/java/reposense/git/GitLog.java, src/main/java/reposense/git/GitShortlog.java, src/main/java/reposense/model/RepoConfiguration.java, src/main/java/reposense/report/ReportGenerator.java, src/main/java/reposense/report/SummaryJson.java, src/main/java/reposense/util/FileUtil.java, src/systemtest/java/reposense/ConfigSystemTest.java, src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java, src/test/java/reposense/authorship/FileAnalyzerTest.java, src/test/java/reposense/commits/CommitInfoAnalyzerTest.java, src/test/java/reposense/git/GitCheckoutTest.java, src/test/java/reposense/git/GitRevListTest.java, src/test/java/reposense/template/GitTestTemplate.java
Fixes #1674
```
zoneId is stored as ZoneId object in CliArguments.java. It is converted 
into String when stored in RepoConfiguration.java. Subsequently, it is 
then converted back to ZoneId when required in FileInfoAnalyzer.java or 
other places.
Such repeated conversion is redundant.
Let's standardize and save zoneId as ZoneId Object across all files.
```
1. `zoneId` in `SummaryJson.java` remains as `String` as changing to `ZoneId` will break `systemtest`. Instead, the constructor will now accept a `ZoneId` input which will subsequent be converted and stored as `String`.
=> [#1674] Convert zoneId String to ZoneId Object

src/main/java/reposense/util/TimeUtil.java, src/test/java/reposense/util/TimeUtilTest.java
Fixes #1793
```
The expected date input is 'dd/mm/yyyy' or 'd/m/yyyy'. With 
extractDate(), inputs like 'dd/mm/yyyyaddedstring' is also accepted.
The same behavior is expected with single-digit date input. However, 
extractDate() cannot process inputs such as '1/1/2022addedstring'.
Let's fix this by updating DATE_FORMAT_REGEX.
```
=> [#1793] TimeUtil: update DATE_FORMAT_REGEX

frontend/package.json
```
After upgrading highlight.js to version 11, the formatting of code in
the code panel breaks.
Let's revert highlight.js back to version 10.
```
It appears that the following lines in `v-segment.vue` do not work with version 11:
https://github.com/reposense/RepoSense/blob/1caadd3cacb3aa293f563053aa18b05512062565/frontend/src/components/v-segment.vue#L15-L18
After reading through the [changelog for `highlight.js` version 11](https://highlightjs.readthedocs.io/en/latest/upgrade-11.html#changes-to-result-data), I noticed that the overall class for each segment will have `language-[language name]` appended to it, but I'm not sure how this affects the way the code is parsed.
=> Hotfix: revert highlight.js from version 11 to 10

build.gradle
```
The current Node version for Gradle is 14.19.0. However, the latest
available version of Node 14 is 14.20.0.
Let's upgrade the Node 14 minor release version in build.gradle.
```
The most recent update to Node 14 is partly due to [vulnerabilities in the underlying OpenSSL]( https://mta.openssl.org/pipermail/openssl-announce/2022-July/000232.html).
Node `14.20.0` release notes: https://nodejs.org/en/blog/release/v14.20.0/
For `build.gradle`, using `14.x` is not allowed:
https://github.com/reposense/RepoSense/blob/507093628bc7a27ba65094a2b7b06a5bbb96423f/build.gradle#L19
unlike in `integration.yml`:
https://github.com/reposense/RepoSense/blob/507093628bc7a27ba65094a2b7b06a5bbb96423f/.github/workflows/integration.yml#L38-L41
=> Gradle: update Node 14 minor release version 

.github/workflows/integration.yml, docs/dg/devOpsGuide.md
```
The Ubuntu 18.04 runner is deprecated and will be fully removed on
2022-12-01, after which the jobs will fail.
Let's remove the Ubuntu 18.04 runner.
Reference: https://github.com/actions/runner-images/issues/6002
```
- The deprecation was [announced on 2 August 2022](https://github.com/actions/runner-images/issues/6002).
- The Ubuntu 22.04 image is now GA, so it has now been made a required check.
- The Ubuntu 18.04 image is now made an optional check.
=> Actions: remove Ubuntu 18.04 runner

.github/workflows/stale.yml
```
The actions/stale GitHub Actions v5 has an issue where updates by the
GitHub Actions bot are recognized as updates. This causes the bot to not
work as intended as the Stale label will be removed.
This issue has already been reported at:
https://github.com/actions/stale/issues/795
Let's downgrade the actions/stale package to v4 until the bug has been
fixed upstream.
```
Upstream issue filed here: https://github.com/actions/stale/issues/795
=> Actions: downgrade actions/stale to v4 due to critical bug

src/main/java/reposense/git/GitLog.java, src/main/java/reposense/git/GitUtil.java
Fixes #1853
```
In Git 2.39, there was a change to the regex library used for MacOS.
This may have caused the git log command with the --author=<pattern>
option, which interprets <pattern> as basic regex, to return nothing on
MacOS.
Let's switch the pattern to extended regex to restore the broken
functionality.
```
One [pull request on Git](https://github.com/git/git/pull/1319) changed the regex library used on MacOS to the native MacOS regex library, from the original Git regex library. This change was part of [Git release 2.39](https://github.com/git/git/blob/v2.39.0/Documentation/RelNotes/2.39.0.txt).
As a result, the way basic regex patterns was interpreted in MacOS `git log` may have changed. This could result in the `git log` command not giving back any results when the `--author` …
=> [#1853] Change git log author regex type

frontend/cypress/tests/codeView/codeView_filterGlob.js, src/main/java/reposense/util/TimeUtil.java, src/test/java/reposense/git/GitLogTest.java
Fixes #452
```
Output from git log is unexpected when dates earlier than the epoch is
provided, or when the date is on or beyond 2100.
Let's modify the getSinceDate and getUntilDate methods in TimeUtil to
check if the date is valid first, and only operate on the valid date.
This helps to prevent the bug while having minimal impact on any of the
existing code utilizing the util.
```
=> [#452] Add date range validation to sinceDate and untilDate

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
```
The current header style of bolding for issue templates is difficult to 
notice compared to the body text. The level 2 header for pull request
template is too large.
Let's update both to use level 3 headings.
```
#1896 provides a preview of what level 3 headers would look like.
=> Change header style for GitHub Issue and PR Templates

src/main/java/reposense/system/LogsManager.java
Fixes #1856 
```
A JavaConcurrentModificationException would occasionally be thrown when
LOGGER_LIST is modified while being streamed. 
Let's add synchronization and fix the concurrency issue.
```
The `setLogFolderLocation` is used in the `ArgsParser::parse` method which is occasionally indirectly called in some tests. `setLogFolderLocation` calls `stream()` on the `LOGGER_LIST` variable. While this happens, there is a small chance that while running tests in parallel, a new `logger` is added to the list which causes the `JavaConcurrentModificationException`. 
It is extremely rare and I managed to get the error on my own machine only once after about 50 runs but I did manage to look at the stack trace and this seems to be the main cause.
=> [#1856] Fix concurrency issue with LOGGER_LIST

frontend/.eslintrc.json, frontend/src/components/c-ramp.vue, frontend/src/components/c-segment.vue, frontend/src/components/c-summary-charts.vue, frontend/src/utils/api.js, frontend/src/views/c-authorship.vue, frontend/src/views/c-zoom.vue
Fixes #1904 
```
ESLint is currently not configured to properly support TypeScript
imports. This results in an error when importing local TypeScript files
with the file extension omitted, which is the default way to import
TypeScript files.
Let's configure ESLint to support TypeScript imports and enforce the
omission of file extensions for .ts and .js files. This will allow us to
pass the lint check while using the default import method, and enforce
consistency throughout the codebase.
```
Adding `plugin:import/typescript` allows ESLint to properly resolve TypeScript imports that don't include the `.ts` file extension, which solves the "Unable to resolve path to module '../..'" error.
```
"import/extensions": [
"error",
{
"js": "never",
"ts": "never"
}
]
```
The above lines configure the …
=> [#1904] Add ESLint support for TypeScript imports

src/main/java/reposense/RepoSense.java, src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java, src/main/java/reposense/model/AuthorConfiguration.java, src/main/java/reposense/model/RepoConfiguration.java, src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
Fixes #1880 
Part of #1879
Part of #1873 
```
AuthorConfiguration.hasAuthorConfigFile is currently a static variable 
that determines whether during the analysis of repo files, a new author
should be added and tracked. If an author config file is provided, an
unrecognized author is ignored, otherwise it is added and tracked.
This might cause parallel runs of test cases at the method level, 
especially system test cases, to have issues.
Let's make AuthorConfiguration.hasAuthorConfigFile a local variable to
the AuthorConfiguration found within each RepoConfiguration.
```
As mentioned by @chan-j-d, this issue is indeed related to #1879. This PR has to be merged in before the PR relevant to #1879. This is the case because in that PR, `AuthorConfiguration.hasAuthorConfigFile` is no longer set …
=> [#1880] Change hasAuthorConfigFile to become a local variable

build.gradle
```
The commons-text dependency has been flagged as vulnerable by OWASP
dependency check. This dependency does not appear to be used anywhere
in the source code.
Let's remove this dependency to reduce the vulnerabilities in the
project.
```
Attached is the relevant OWASP dependency check report
[RepoSense Dependency-Check Report.pdf](https://github.com/reposense/RepoSense/files/10830467/RepoSense.Dependency-Check.Report.pdf)
=> Gradle: remove unneeded commons-text dependency

build.gradle
```
The gradleVersion property of the wrapper fixes the Gradle version used
by the wrapper. This is confusing and difficult to maintain as Gradle
gets upgraded.
Let's remove the definition of the gradleVersion property in the
wrapper. This results in the current version of Gradle itself being used
for the wrapper too.
```
I noticed that I missed out on updating the wrapper version when doing [previous upgrades of Gradle versions](https://github.com/reposense/RepoSense/pull/1919#pullrequestreview-1328993999).
Looking at the Gradle docs, it turns out that the `gradleVersion` property is for defining [what version of Gradle the wrapper itself is using](https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:gradleVersion). By default, it …
=> Remove Gradle wrapper version definition

docs/dg/styleGuides.md, frontend/.eslintrc.json, frontend/src/types/window.ts, frontend/src/utils/user.ts
Fixes #1945 
```
Currently, our ESLint ruleset does not enforce certain formatting rules
for TypeScript code, such as delimiters in TypeScript interfaces and
spacing in type annotations.
Let's update the ESLint ruleset to check for proper delimiters and
spacing in type annotations. This will enforce consistency throughout
the codebase and improve code readability.
```
Most of the information is in #1945. The first rule enforces semicolons as delimiters in TypeScript interfaces, and the second rule enforces the following format for type annotations: `foo: string` over `foo : string` or `foo :string`.
=> [#1945] Enforce stricter formatting rules for TypeScript files

.github/workflows/surge.yml
Fixes #1967
```
surge.yml currently uses set-output to extract and save the PR number
for use as part of the surge.sh preview domain. However, GitHub will be
deprecating set-output for security reasons.
Let's update surge.yml to use the new GITHUB_OUTPUT environment files
instead.
```
The change were as per [GitHub's article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
While our surge.sh preview is still currently down, the correctness of this PR can be checked against the link produced.
=> [#1967] Use GitHub environmental files instead of set-output

src/main/java/reposense/model/ConfigRunConfiguration.java
Fixes #1881
```
Currently, for both detection of author config and group config, it relies 
on running the code normally as if the file is always present and 
catching the FileNotFoundException to determine 
if the file is not present.
Let's refactor the code to detect if the file does not exist using 
an `if` block instead of catching it in the try-catch 
block
```
=> [#1881] Check if author config file exists instead of detecting it via an exception

frontend/src/components/c-summary-charts.vue
Fixes #2027 
```
Currently, users are unable to select a zoom range that includes the until date.
This results in misleading data being presented to users.
```
Upon further investigation, the bug is caused by inaccurate logic in the `openTabZoomSubrange` method in `c-summary-charts.vue`.
```
if (this.drags.length === 2 && this.drags[1] - this.drags[0]) {
const tdiff = (new Date(this.filterUntilDate)).valueOf() - (new Date(this.filterSinceDate)).valueOf();
const idxs = this.drags.map((x) => (x * tdiff) / 100);
const tsince = window.getDateStr(new Date(this.filterSinceDate).getTime() + idxs[0]);
const tuntil = window.getDateStr(new Date(this.filterSinceDate).getTime() + idxs[1]);
this.drags = [];
this.openTabZoom(user, tsince, tuntil, isMerged);
}
```
In line 2, the const `tdiff` is …
=> [#2027] Fix date range bug

frontend/cypress/package-lock.json, frontend/cypress/package.json
Fixes #2039
```
Chrome bug is causing cypress to fail to open a browser on Github 
Actions, causing frontend tests and CI to fail. Upgrading cypress 
to greater than 12.15.0 will fix this issue.
Let's upgrade cypress to fix the failing CI. 
```
More information about the issue can be found in #2039 and the cypress issue https://github.com/cypress-io/cypress/issues/27804 with the solution taken from https://github.com/cypress-io/cypress/issues/27804#issuecomment-1721476731.
=> [#2039] Update cypress minimum requirement to 12.15.0

frontend/src/components/c-segment.vue
Part of #1936 
```
Currently, there is still some JavaScript code which remains 
unmigrated. This allows for type unsafe code to be written, 
potentially resulting in unintended behavior.
Let's migrate the rest of the JavaScript code to TypeScript 
code to facilitate future changes to the code.
```
* Converted JavaScript code in `c-segment.vue` to TypeScript.
* Modified potentially dangerous code (see below).
The following code makes use of the behavior of the `||` operator where the result will be the first operand given that the first operand is not `false` or `null` or any value that is represented by the value `0`. In this case, `this.segment.knownAuthor` has been declared to be `string` or `null` in `segment.ts`. The consequence of this would be that the result, given that the first …
=> [#1936] Migrate c-segment.vue to typescript

src/main/java/reposense/parser/ArgsParser.java, src/test/java/reposense/parser/ArgsParserTest.java
Fixes #1989
```
Reduce scope of try-catch block tin ArgsParser::parse
The old scope of the try block in ArgsParser::parse 
is too permissive, making it less apparent which 
methods throw the associated exceptions.
Let's reduce the scope of the try block in 
ArgsParser::parse.
```
NA
=> [#1989] Reduce scope of try-catch block in ArgsParser::parse

src/main/java/reposense/parser/RepoConfigCsvParser.java
Fixes #2073 
```
The current implementation of `RepoConfigCsvParser::processLine`
contains code that has 3 levels of indentation, making it 
difficult to read and maintain.
With the proposed changes, the level of deep nesting has 
been reduced to 2 levels, making the code more 
readable and maintainable.
Let's move to refactor and clean up the code to avoid 
arrowhead-style codes for better readability and 
maintainability.
```
NA
=> [#2073] Refactor `RepoConfigCsvParser::processLine` method to avoid arrowhead style code

docs/dg/settingUp.md
Fixes #2082 
```
Replace the command `npm -v` with `node -v`.
This displays the node version instead of the npm version.
```
=> [#2082] Fix typo in command in Setting Up page

frontend/cypress/tests/chartView/chartView_zoomFeature.cy.js
Fixes #2111 
Fixes #2066 also
```
Fix nondeterministically failing zoomFeature cypress test
The "range changes in chartview should reflect in zoom" test in
chartView_zoomFeature.cy.js fails because as time passes, the
coordinates in the ramp that correspond to the desired zoom area
change.
Let's add an "until" filter to the relevant cypress tests to stop this
from happening
```
=> [#2111] Fix failing zoomFeature cypress test

frontend/src/components/c-segment.vue
Fixes #2134
```
The code highlighting is not working as the colors are not being
recognized by the newly extracted c-segment.vue file. This is because
the defined colors were not imported into the file.  
Let us add the color styles import to restore code highlighting
functionality.  
```
NIL
=> [#2134] Fix broken code highlighting in Code Panel

docs/ug/usingReports.md, frontend/cypress/tests/chartView/chartView_toolBar_searchBox.cy.js, frontend/src/views/c-summary.vue
Reverts reposense/RepoSense#2116 to fix #2164 
```
Reverts PR #2116 to fix single group bug
Merging PR #2116 has caused all analysed charts to appear in a single group. 
Let us revert that PR as a hotfix to restore the original behaviour while we
investigate a solution.    
```
=> [#2164] Revert "[#2109] Add search by tag functionality"

frontend/cypress/config/author-config.csv, frontend/cypress/tests/chartView/chartView_mergeGroup.cy.js, frontend/cypress/tests/chartView/chartView_scrollToActiveRepo.cy.js, frontend/cypress/tests/chartView/chartView_showTags.cy.js, frontend/src/components/c-summary-charts.vue
Fixes #2195 
```
Add cypress test for show tag when grouping by author and by none
Currently, there are no Cypress tests to test the behaviour of the show
tag feature when the report is grouped by author or grouped by none.
Let's add a test for this to ensure the feature is working properly.
```
=> [#2195] Add cypress test for show tag when grouping by author and by none

docs/_markbind/layouts/body.md
Fixes a typo that caused the page navigation menu to not appear:
before:
after:
=> Fix missing PageNav in docs

frontend/src/components/c-file-type-checkboxes.vue
Fixes #2222
```
Fix Checkboxes Line Count
In c-file-type-checkboxes, the method getLabel() should show fileType,
lineCount and effective line count, but it currently shows fileType,
blankLineCount and effective line count instead.
Let's fix the code to show the correct counts.
```
=> [#2222] Fix Checkboxes Line Count

frontend/src/styles/panels.scss, frontend/src/views/c-authorship.vue, frontend/src/views/c-zoom.vue
Resolves #2127
```
Align panel titles
The title text on the left panel is not flushed to the top because it
is a header.
There are several types of title texts on the right panel. Initially,
some were headers and others were not. There was padding to ensure that
those which were not headers were not flushed to the top.  However, this
meant that those headers were lower than expected and not aligned. 
To align the texts, let us remove the padding for the right panel and
set the first element on the right panel as a header. 
```
Before:
After:
=> Align right panel with welcome title

docs/ug/authorConfigSyntax.md, src/main/java/reposense/authorship/FileInfoAnalyzer.java
Fixes #2220
```
As branches are already specified in the first cell, the 2nd cell
specifying the branch may only confuse the user.
Let's remove the contents of the second cell.
```
Due to intellij recognizing a pipe operator as a column separator, the preview looks different compared to the rendering on github.
Before:
After:
=> [#2220] Empty cell in UG

.github/workflows/integration.yml, .github/workflows/pending.yml
Fixes #2273
```
Upgrade artifact actions to v4
All workflows using v3 of artifact actions automatically fail from
2025-01-30 onwards due to deprecation.
Let's upgrade to the latest version (v4).
```
=> [#2273] Update workflows to use v4 of artifact actions

docs/dg/learningBasics.md
Fixes #2265 
Fixes #2267 
```
Fix outdated suggested solution for backend Task 1.
The suggested solution for backend Task 1 in Developer Guide under
Learning the Basics is currently outdated due to past refactoring.
Let's update the documentation for backend Task 1.
```
=> [#2265][#2267]Fix outdated suggested solution for backend Task 1

build.gradle, frontend/cypress/tests/chartView/chartView_optimiseTimeline.cy.js
Fixes #2266
```
Set UTC timezone for test reports
Running Cypress tests locally uses system's default timezone
(UTC+8), causing 3 tests that check for dates to fail. These 3 tests
pass on GitHub Actions as the system's default timezone is UTC.
Let's standardize the timezone for all cypress tests to UTC.
```
Run `./gradlew frontendTests` or `./gradlew cypress` locally to verify all tests are passing.
3 previously failing tests:
* chartView/chartView_mergeCommits.cy.js show merge commits in summary chart
* chartView/chartView_optimiseTimeline.cy.js start and end date indicators should exist
* chartView/chartView_optimiseTimeline.cy.js zoom panel range should work correctly when timeline is optimised
=> [#2266] Fix Cypress tests that fail locally

.github/workflows/integration.yml, docs/dg/learningBasics.md, src/main/java/reposense/util/FileUtil.java, src/main/java/reposense/util/adapters/DateSerializer.java, src/main/java/reposense/util/adapters/ZoneSerializer.java
Fixes #2262 
```
Update GSON type adapter adding methods
The registration of custom adapters for ZoneID and LocalDateTime causes
The JsonIOException to pop up when trying to run the jar file in java
17.
Let's use the registerTypeHierarchyAdapter method to add the custom
adapters instead.
```
Here are some reference resources I found online:
- https://stackoverflow.com/questions/74924830/why-is-gson-looking-for-java-time-zoneregion-when-serializing-java-time-zoneid
- https://www.javadoc.io/doc/com.google.code.gson/gson/2.6.2/com/google/gson/GsonBuilder.html#registerTypeHierarchyAdapter-java.lang.Class-java.lang.Object
=> [#2262] Update type adapter adding methods for gson builder

frontend/src/styles/style.scss
Fixes #2213 
```
Fix the <hr> element not appearing in report.
The <hr> element in title.md and blurbs.md is not appearing in the
report because the normalise.css defaults the <hr> element style.
Let's override the <hr> element style in style.scss so that it will
appear in the report.
```
=> [#2213] Fix hr element not appearing in report

frontend/.eslintrc.json, frontend/src/store/store.ts, frontend/src/types/window.ts, frontend/src/utils/repo-sorter.ts
Fixes #2190
```
Add ESLint rule to enforce commas between types
This PR overrides the default behavior of requiring semicolon
separators for both interface and type in ESLint, to require semicolon
separator for interface and comma separator for type
```
=> [#2190] Add ESLint rule to enforce commas between types

frontend/package-lock.json, frontend/package.json
Fixes #2327
```
Upgrade Vite version to 6.2.2
To address 4 moderate vulnerability issues in npm.
```
=> [#2327] Upgrade Vite version to 6.2.2

frontend/package-lock.json, frontend/package.json, frontend/vite.config.mts
Fixes #2326
```
Optimize Vite Chunk Size
Did the following optimizations to reduce max chunk size from ~1.5MB to
~0.8MB. 
Manually split the Vue libraries and large utility libraries into
their own chunks. This reduces the max chunk size since we now have 3
main files instead of having everything in the index file as one large
chunk.
Also set the chunkSizeWarningLimit to 1000 for now, since the
highligh.js package is already 862.99kB on its own.
Note:
Command to generate the breakdown of chunk sizes:  
npx vite-bundle-visualizer -t sunburst 
```
Before:
After:
=> [#2326] Optimize Vite Chunk Size

frontend/cypress/tests/chartView/chartView_showTags.cy.js, frontend/src/types/window.ts, frontend/src/utils/api.ts, frontend/src/utils/repo-sorter.ts, frontend/src/views/c-summary.vue
Fixes #2332, #2362
```
Frontend Sort Function Enhancement
Improve frontend sort function efficiency for descending order by
refactoring to use boolean, and modify the sort comparator to take in 1
additional argument `isDesc` instead of calling `.reverse()` after
doing an ascending sort.
Important: A Cypress test case was modified to account for corrected
behavior because previous code for 'groupByAuthors' contains a bug
where we use `sortingWithinOption` instead of `sortWithinOption`, thus
causing the sort order within a group to be arbitrary if we sort by
'title' 
since the property doesn't exist and we are sorting an array of blank
strings.
```
=> [#2332] Frontend Sort Function Bugfix and Enhancement

docs/ug/reportConfig.md, src/main/java/reposense/model/OneStopConfigRunConfiguration.java, src/main/java/reposense/model/reportconfig/ReportAuthorDetails.java, src/systemtest/resources/ReportConfigSystemTest/report-config.yaml, src/test/java/reposense/model/OneStopConfigRunConfigurationTest.java, src/test/java/reposense/model/reportconfig/ReportAuthorDetailsTest.java, src/test/java/reposense/model/reportconfig/ReportConfigurationTest.java, src/test/java/reposense/parser/ReportConfigYamlParserTest.java, src/test/resources/ReportConfigYamlParserTest/report-config-valid.yaml, src/test/resources/RunConfigurationDeciderTest/both-configs/report-config.yaml
Fixes #2447
```
Add support for multiple author names.
This is similar to how the parser handles
authors emails.
```
Users can specify multiple author-name in the following way:
```yaml
author-git-author-name:
- name1
- name2
- name3
```
=> [#2447] Add support for multiple git author names
